# Generated by Django 5.2 on 2026-04-30 22:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item no Carrinho',
                'verbose_name_plural': 'Itens no Carrinho',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='ca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CA (Certificado de Aprovação)'),
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AddField(
            model_name='item',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº do Lote'),
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca/Fabricante'),
        ),
        migrations.AddField(
            model_name='item',
            name='validade_ca',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do CA'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='departamento',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('PROD', 'Produção'), ('MAN', 'Manutenção'), ('TI', 'Tecnologia'), ('MKT', 'Marketing'), ('VEND', 'Vendas'), ('RH', 'Recursos Humanos'), ('FIN', 'Financeiro'), ('JUR', 'Jurídico'), ('LOG', 'Logística'), ('QUAL', 'Qualidade'), ('PESQ', 'Pesquisa'), ('OUT', 'Outros')], default='OUT', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='itens_fotos/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('PAR', 'Par'), ('DZ', 'Dúzia'), ('RL', 'Rolo'), ('FL', 'Folha')], default='UN', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='saida',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ADM', 'Administrativo'), ('PROD', 'Produção'), ('MAN', 'Manutenção'), ('TI', 'Tecnologia'), ('MKT', 'Marketing'), ('VEND', 'Vendas'), ('RH', 'Recursos Humanos'), ('FIN', 'Financeiro'), ('JUR', 'Jurídico'), ('LOG', 'Logística'), ('QUAL', 'Qualidade'), ('PESQ', 'Pesquisa'), ('OUT', 'Outros')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='saida',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='almoxarifado.item'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='item_codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='item_nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='saida',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saida',
            name='solicitante',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['codigo'], name='almoxarifad_codigo_c8cc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['departamento'], name='almoxarifad_departa_28b298_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['lote'], name='almoxarifad_lote_00cc39_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['ca'], name='almoxarifad_ca_bac3c7_idx'),
        ),
        migrations.AddField(
            model_name='carrinhosolicitacao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.item'),
        ),
        migrations.AlterUniqueTogether(
            name='carrinhosolicitacao',
            unique_together={('usuario', 'item')},
        ),
    ]
