# Generated by Django 5.2 on 2026-05-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_carrinhosolicitacao_item_ca_item_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
    ]
