# Generated by Django 5.2 on 2026-05-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_alter_item_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tamanho',
            field=models.CharField(blank=True, help_text='Ex: P, M, G, GG, 10x15cm, Único', max_length=50, null=True, verbose_name='Tamanho/Medida'),
        ),
    ]
