# Generated by Django 5.2 on 2026-05-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_item_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='departamento',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('PROD', 'Produção'), ('MAN', 'Manutenção'), ('TI', 'Tecnologia'), ('FAC', 'Facilities'), ('LAB', 'Laboratório'), ('LOG', 'Logística'), ('EPI', 'Epi'), ('OUT', 'Outros')], default='OUT', max_length=4),
        ),
        migrations.AlterField(
            model_name='saida',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ADM', 'Administrativo'), ('PROD', 'Produção'), ('MAN', 'Manutenção'), ('TI', 'Tecnologia'), ('FAC', 'Facilities'), ('LAB', 'Laboratório'), ('LOG', 'Logística'), ('EPI', 'Epi'), ('OUT', 'Outros')], max_length=4, null=True),
        ),
    ]
