# Generated by Django 5.2 on 2026-05-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_alter_item_departamento_alter_saida_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('numero_nota', models.CharField(max_length=20)),
                ('fornecedor_nome', models.CharField(max_length=200)),
                ('cnpj_fornecedor', models.CharField(max_length=18)),
                ('data_emissao', models.DateField()),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('xml_arquivo', models.FileField(blank=True, null=True, upload_to='nfe_xmls/')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='itens_fotos/', verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_nota', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.item')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_nota', to='almoxarifado.entradanotafiscal')),
            ],
        ),
    ]
