# Generated by Django 5.2 on 2026-05-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0007_entradanotafiscal_alter_item_foto_itementrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='cnpj_fornecedor',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='itementrada',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_nota', to='almoxarifado.item'),
        ),
    ]
