# Generated by Django 5.2 on 2026-05-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_alter_entradanotafiscal_cnpj_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(choices=[('UN', 'UN'), ('CX', 'CX'), ('PCT', 'PCT'), ('KG', 'KG'), ('G', 'G'), ('L', 'L'), ('ML', 'ML'), ('M', 'M'), ('CM', 'CM'), ('PAR', 'Par'), ('DZ', 'DZ'), ('RL', 'RL'), ('FL', 'FL')], default='UN', max_length=3),
        ),
    ]
