# Generated by Django 5.2 on 2026-05-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_alter_item_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome'], 'permissions': [('pode_ver_almoxarifado', 'Pode visualizar itens do almoxarifado'), ('pode_gerenciar_almoxarifado', 'Pode gerenciar almoxarifado (CRUD)')], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
