# Generated by Django 5.2 on 2026-05-20 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_alter_item_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(default='http://localhost:8080', help_text='URL base da API Evolution (ex: http://localhost:8080)', max_length=255, verbose_name='URL da API Evolution')),
                ('api_key', models.CharField(blank=True, help_text='Chave da API Evolution (Global API Key)', max_length=255, null=True, verbose_name='API Key')),
                ('instance_name', models.CharField(blank=True, help_text='Nome da instância do WhatsApp que irá enviar as mensagens', max_length=100, null=True, verbose_name='Instância WhatsApp')),
                ('numeros_destino', models.TextField(blank=True, help_text='Números de WhatsApp para receber as notificações (separados por vírgula ou linha)', null=True, verbose_name='Números de Destino')),
                ('notificar_estoque_baixo', models.BooleanField(default=True, verbose_name='Notificar estoque baixo')),
                ('notificar_estoque_zerado', models.BooleanField(default=True, verbose_name='Notificar estoque zerado')),
                ('notificar_reposicao', models.BooleanField(default=True, verbose_name='Notificar quando item for reposto')),
                ('template_estoque_baixo', models.TextField(default='🔴 *ALERTA DE ESTOQUE BAIXO!*\n\n*Item:* {nome}\n*Código:* {codigo}\n*Localização:* {localizacao}\n*Departamento:* {departamento}\n\n📦 *Estoque atual:* {quantidade} {unidade}\n⚠️ *Estoque mínimo:* {minimo} {unidade}\n\n📌 *Sugestão:* Solicitar compra de {sugestao} {unidade}', verbose_name='Template - Estoque Baixo')),
                ('template_estoque_zerado', models.TextField(default='🔴 *ESTOQUE ZERADO!*\n\n*Item:* {nome}\n*Código:* {codigo}\n*Localização:* {localizacao}\n*Departamento:* {departamento}\n\n📦 *Estoque atual:* 0 {unidade}\n⚠️ *Estoque mínimo:* {minimo} {unidade}\n\n🚨 *URGENTE:* Necessário compra imediata!', verbose_name='Template - Estoque Zerado')),
                ('template_reposicao', models.TextField(default='✅ *ITEM REPOSTO!*\n\n*Item:* {nome}\n*Código:* {codigo}\n*Localização:* {localizacao}\n*Departamento:* {departamento}\n\n📦 *Novo estoque:* {nova_quantidade} {unidade}\n➕ *Quantidade adicionada:* {adicionado} {unidade}\n\n📊 *Status:* {status}', verbose_name='Template - Reposição')),
                ('verificar_ao_adicionar', models.BooleanField(default=True, verbose_name='Verificar ao adicionar/editar item')),
                ('verificar_agendado', models.BooleanField(default=True, verbose_name='Verificação agendada')),
                ('horario_verificacao', models.TimeField(default='08:00', verbose_name='Horário da verificação agendada')),
                ('repetir_notificacao', models.BooleanField(default=False, verbose_name='Repetir notificação enquanto estiver baixo')),
                ('intervalo_repeticao', models.IntegerField(default=24, verbose_name='Intervalo de repetição (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Sistema ativo')),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificações',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(default='http://localhost:8080', help_text='URL base da API Evolution (ex: http://localhost:8080)', max_length=255, verbose_name='URL da API Evolution')),
                ('api_key', models.CharField(blank=True, help_text='Chave global da API Evolution', max_length=255, null=True, verbose_name='Global API Key')),
                ('instance_name', models.CharField(blank=True, help_text='Nome da instância do WhatsApp (ex: "instancia_principal")', max_length=100, null=True, verbose_name='Nome da Instância')),
                ('numeros_destino', models.TextField(blank=True, help_text='Números que receberão as notificações (separados por vírgula ou linha). Ex: 5511999999999, 5511988888888', null=True, verbose_name='Números de WhatsApp')),
                ('notificar_estoque_baixo', models.BooleanField(default=True, verbose_name='Notificar estoque baixo')),
                ('notificar_estoque_zerado', models.BooleanField(default=True, verbose_name='Notificar estoque zerado')),
                ('notificar_reposicao', models.BooleanField(default=True, verbose_name='Notificar quando for reposto')),
                ('template_estoque_baixo', models.TextField(default='🔴 *ALERTA DE ESTOQUE BAIXO!*\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n🏢 *Departamento:* {departamento}\n\n📊 *Estoque atual:* {quantidade} {unidade}\n⚠️ *Estoque mínimo:* {minimo} {unidade}\n\n📌 *Sugestão de compra:* {sugestao} {unidade}\n\n🔔 Esta é uma mensagem automática do sistema de Almoxarifado.')),
                ('template_estoque_zerado', models.TextField(default='🔴 *ESTOQUE ZERADO!* 🚨\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n🏢 *Departamento:* {departamento}\n\n📊 *Estoque atual:* 0 {unidade}\n⚠️ *Estoque mínimo:* {minimo} {unidade}\n\n🚨 *URGENTE - Necessário compra imediata!*\n\n🔔 Esta é uma mensagem automática do sistema de Almoxarifado.')),
                ('template_reposicao', models.TextField(default='✅ *ITEM REPOSTO!*\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n\n📊 *Novo estoque:* {nova_quantidade} {unidade}\n➕ *Quantidade adicionada:* {adicionado} {unidade}\n📈 *Status:* {status}\n\n🔔 Esta é uma mensagem automática do sistema de Almoxarifado.')),
                ('ativo', models.BooleanField(default=True, verbose_name='Sistema ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp do Almoxarifado',
                'verbose_name_plural': 'Configurações WhatsApp do Almoxarifado',
            },
        ),
        migrations.CreateModel(
            name='HistoricoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('estoque_zerado', 'Estoque Zerado'), ('reposicao', 'Reposição')], max_length=20)),
                ('destinatario', models.CharField(max_length=50, verbose_name='Destinatário')),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro', models.TextField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='almoxarifado.item')),
            ],
            options={
                'verbose_name': 'Histórico de Notificação',
                'verbose_name_plural': 'Históricos de Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoNotificacaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('baixo', 'Estoque Baixo'), ('zerado', 'Estoque Zerado'), ('reposicao', 'Reposição')], max_length=20)),
                ('destinatario', models.CharField(max_length=50, verbose_name='Destinatário')),
                ('mensagem', models.TextField(verbose_name='Mensagem enviada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('api_response', models.TextField(blank=True, null=True, verbose_name='Resposta da API')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_whatsapp', to='almoxarifado.item')),
            ],
            options={
                'verbose_name': 'Histórico de Notificação',
                'verbose_name_plural': 'Históricos de Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('estoque_zerado', 'Estoque Zerado'), ('reposicao', 'Reposição')], max_length=20)),
                ('ultima_notificacao', models.DateTimeField(auto_now_add=True)),
                ('notificacoes_enviadas', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='almoxarifado.item')),
            ],
            options={
                'unique_together': {('item', 'tipo')},
            },
        ),
    ]
