# Generated by Django 5.2 on 2026-05-23 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_configuracaonotificacao_configuracaowhatsapp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertaestoque',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='alertaestoque',
            name='item',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoNotificacao',
        ),
        migrations.RemoveField(
            model_name='historiconotificacao',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='configuracaowhatsapp',
            options={'verbose_name': 'Configuração WhatsApp', 'verbose_name_plural': 'Configurações WhatsApp'},
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='api_url',
            field=models.CharField(default='http://localhost:8080', max_length=255, verbose_name='URL da API Evolution'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='instance_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Instância'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='notificar_estoque_baixo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='notificar_estoque_zerado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='notificar_reposicao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='numeros_destino',
            field=models.TextField(blank=True, help_text='Separados por vírgula. Ex: 5511999999999,5511988888888', null=True, verbose_name='Números de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_baixo',
            field=models.TextField(default='🔴 *ALERTA DE ESTOQUE BAIXO!*\n\n📦 *Item:* {nome}\n📊 *Estoque atual:* {quantidade} {unidade}\n⚠️ *Mínimo:* {minimo} {unidade}\n📍 *Local:* {localizacao}'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_zerado',
            field=models.TextField(default='🔴 *ESTOQUE ZERADO!* 🚨\n\n📦 *Item:* {nome}\n⚠️ *Necessário compra imediata!*'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_reposicao',
            field=models.TextField(default='✅ *ITEM REPOSTO!*\n\n📦 *Item:* {nome}\n📊 *Novo estoque:* {nova_quantidade} {unidade}\n➕ *Adicionado:* {adicionado} {unidade}'),
        ),
        migrations.AlterField(
            model_name='historiconotificacaoalmoxarifado',
            name='api_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiconotificacaoalmoxarifado',
            name='destinatario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiconotificacaoalmoxarifado',
            name='erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiconotificacaoalmoxarifado',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='ca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='itens_fotos/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamanho/Medida'),
        ),
        migrations.AlterField(
            model_name='item',
            name='validade_ca',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AlertaEstoque',
        ),
        migrations.DeleteModel(
            name='HistoricoNotificacao',
        ),
    ]
