# Generated by Django 5.2 on 2026-05-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0012_alter_alertaestoque_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='api_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='instance_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='numeros_destino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_baixo',
            field=models.TextField(default='🔴 *ALERTA DE ESTOQUE BAIXO!*\n\n*Item:* {nome}\n*Estoque:* {quantidade} {unidade}\n*Mínimo:* {minimo} {unidade}'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_zerado',
            field=models.TextField(default='🔴 *ESTOQUE ZERADO!*\n\n*Item:* {nome}\n*Necessário compra imediata!'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_reposicao',
            field=models.TextField(default='✅ *ITEM REPOSTO!*\n\n*Item:* {nome}\n*Novo estoque:* {nova_quantidade} {unidade}'),
        ),
    ]
