# Generated by Django 5.2 on 2026-05-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0013_alter_configuracaowhatsapp_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaowhatsapp',
            name='numeros_destino',
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='numeros_padrao',
            field=models.TextField(blank=True, help_text='Números padrão separados por vírgula', null=True),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='numeros_por_departamento',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_baixo',
            field=models.TextField(default='🔴 *ALERTA DE ESTOQUE BAIXO!*\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n🏢 *Departamento:* {departamento}\n\n📊 *Estoque atual:* {quantidade} {unidade}\n⚠️ *Estoque mínimo:* {minimo} {unidade}\n\n📌 *Sugestão de compra:* {sugestao} {unidade}'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_zerado',
            field=models.TextField(default='🔴 *ESTOQUE ZERADO!* 🚨\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n🏢 *Departamento:* {departamento}\n\n⚠️ *URGENTE - Necessário compra imediata!*'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_reposicao',
            field=models.TextField(default='✅ *ITEM REPOSTO!*\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n\n📊 *Novo estoque:* {nova_quantidade} {unidade}\n➕ *Quantidade adicionada:* {adicionado} {unidade}\n📈 *Status:* {status}'),
        ),
    ]
