# Generated by Django 5.2 on 2026-05-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0014_remove_configuracaowhatsapp_numeros_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='departamentos_ativos',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Departamentos Ativos'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Dias da Semana'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='horario_agendado',
            field=models.TimeField(default='08:00', verbose_name='Horário do Envio Agendado'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='intervalo_repeticao',
            field=models.IntegerField(default=24, verbose_name='Intervalo de Repetição (horas)'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='notificar_baixo',
            field=models.BooleanField(default=True, verbose_name='Notificar Estoque Baixo'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='notificar_zerado',
            field=models.BooleanField(default=True, verbose_name='Notificar Estoque Zerado'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='repetir_notificacoes',
            field=models.BooleanField(default=False, verbose_name='Repetir Notificações'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='template_resumo',
            field=models.TextField(default='📊 *RESUMO DIÁRIO DE ESTOQUE*\n\n📅 Data: {data}\n🏢 Departamento: {departamento}\n\n📦 *ITENS COM ESTOQUE BAIXO:* ({total_baixo})\n{lista_baixo}\n\n⚠️ *ITENS ZERADOS:* ({total_zerado})\n{lista_zerado}\n\n🔔 Este é um resumo automático do sistema de Almoxarifado.', verbose_name='Template de Resumo'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='tipo_envio',
            field=models.CharField(choices=[('tempo-real', '🚀 Tempo Real'), ('agendado', '📅 Agendado'), ('ambos', '🔄 Ambos')], default='tempo-real', max_length=20, verbose_name='Tipo de Envio'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='notificar_reposicao',
            field=models.BooleanField(default=True, verbose_name='Notificar Reposição'),
        ),
    ]
