# Generated by Django 5.2 on 2026-05-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0015_configuracaowhatsapp_departamentos_ativos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='ultima_notificacao_agendada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Notificação Agendada'),
        ),
    ]
