# Generated by Django 5.2 on 2026-05-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0016_configuracaowhatsapp_ultima_notificacao_agendada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_baixo',
            field=models.TextField(default='🔴 *ESTOQUE BAIXO!*\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n🏢 *Departamento:* {departamento}\n\n📊 *Estoque atual:* {quantidade} {unidade}\n⚠️ *Estoque mínimo:* {minimo} {unidade}\n\n📌 *Sugestão de compra:* {sugestao} {unidade}'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_resumo',
            field=models.TextField(default='📊 *RESUMO DIÁRIO*\n\n📅 Data: {data}\n🏢 Departamento: {departamento}\n\n📦 *ESTOQUE BAIXO:* ({total_baixo})\n{lista_baixo}\n\n⚠️ *ITENS ZERADOS:* ({total_zerado})\n{lista_zerado}\n\n🔔 Este é um resumo automático do sistema de Almoxarifado.', verbose_name='Template de Resumo'),
        ),
    ]
