# Generated by Django 5.2 on 2026-05-31 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0017_alter_configuracaowhatsapp_template_estoque_baixo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradanotafiscal',
            options={'ordering': ['-data_recebimento'], 'verbose_name': 'Entrada de Nota Fiscal', 'verbose_name_plural': 'Entradas de Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='itementrada',
            options={'verbose_name': 'Item da Nota Fiscal', 'verbose_name_plural': 'Itens da Nota Fiscal'},
        ),
        migrations.RemoveField(
            model_name='configuracaowhatsapp',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='configuracaowhatsapp',
            name='horario_agendado',
        ),
        migrations.RemoveField(
            model_name='configuracaowhatsapp',
            name='ultima_notificacao_agendada',
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor_unitario',
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='atualizado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_estoque_zerado',
            field=models.TextField(default='🔴 *ESTOQUE ZERADO!* 🚨\n\n📦 *Item:* {nome}\n🏷️ *Código:* {codigo}\n📍 *Localização:* {localizacao}\n🏢 *Departamento:* {departamento}\n\n⚠️ *URGENTE - Necessário compra imediata!'),
        ),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='template_resumo',
            field=models.TextField(default='📊 *RESUMO DIÁRIO DE ESTOQUE*\n\n📅 Data: {data}\n🏢 Departamento: {departamento}\n\n📦 *ITENS COM ESTOQUE BAIXO:* ({total_baixo})\n{lista_baixo}\n\n⚠️ *ITENS ZERADOS:* ({total_zerado})\n{lista_zerado}\n\n🔔 Este é um resumo automático do sistema de Almoxarifado.', verbose_name='Template de Resumo'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='chave_acesso',
            field=models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='cnpj_fornecedor',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='data_recebimento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='fornecedor_nome',
            field=models.CharField(max_length=200, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='numero_nota',
            field=models.CharField(max_length=20, verbose_name='Número da Nota'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='entradanotafiscal',
            name='xml_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='nfe_xmls/', verbose_name='XML da Nota'),
        ),
        migrations.AlterField(
            model_name='itementrada',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_nota', to='almoxarifado.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itementrada',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_nota', to='almoxarifado.entradanotafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='itementrada',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itementrada',
            name='quantidade_nota',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade na Nota'),
        ),
        migrations.CreateModel(
            name='AgendamentoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('dias_semana', models.JSONField(blank=True, default=list, null=True, verbose_name='Dias da Semana (0=domingo a 6=sábado)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='almoxarifado.configuracaowhatsapp')),
            ],
            options={
                'verbose_name': 'Agendamento de Notificação',
                'verbose_name_plural': 'Agendamentos de Notificações',
                'ordering': ['horario'],
            },
        ),
    ]
