# Generated by Django 5.2 on 2026-05-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0018_alter_entradanotafiscal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='horario_agendado',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
    ]
