# Generated by Django 5.2 on 2026-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0019_configuracaowhatsapp_dias_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instância')),
                ('status', models.CharField(default='disconnected', max_length=20, verbose_name='Status')),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instância WhatsApp',
                'verbose_name_plural': 'Instâncias WhatsApp',
                'ordering': ['nome'],
            },
        ),
    ]
