# Generated by Django 5.2 on 2026-05-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0020_instanciawhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='ultima_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
