# Generated by Django 5.2 on 2026-08-10 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0021_configuracaowhatsapp_ultima_verificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraNotificacaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ESTOQUE_BAIXO', 'Estoque abaixo do mínimo'), ('ESTOQUE_ABAIXO_X', 'Estoque abaixo de X'), ('ESTOQUE_ZERADO', 'Estoque zerado'), ('ESTOQUE_REPOSTO', 'Estoque reposto'), ('VENCE_EM', 'Vencimento antecipado'), ('VENCE_HOJE', 'Vence hoje'), ('VENCIDO', 'Produto vencido')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_limite', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('dias_antes_vencimento', models.JSONField(blank=True, default=list)),
                ('departamentos', models.JSONField(blank=True, default=list)),
                ('repetir', models.BooleanField(default=False)),
                ('intervalo_repeticao_horas', models.PositiveIntegerField(default=24)),
                ('template_mensagem', models.TextField(blank=True, default='🔔 *ALMOXARIFADO*\n{evento}\n\n📦 {nome}\n🔢 Código: {codigo}\n🏷️ Lote: {lote}\n📊 Saldo: {quantidade} {unidade}\n📅 Vencimento: {vencimento}\n⏳ Dias: {dias}\n')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DadosValidadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fabricacao', models.DateField(blank=True, db_index=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_validade', to='almoxarifado.item')),
            ],
            options={
                'verbose_name': 'Validade do item',
                'verbose_name_plural': 'Validades dos itens',
                'ordering': ['data_vencimento', 'item__nome'],
            },
        ),
        migrations.CreateModel(
            name='EstadoNotificacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_anterior', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_notificacao', to='almoxarifado.item')),
            ],
        ),
        migrations.CreateModel(
            name='ImportacaoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLANILHA', 'Planilha'), ('NFE_XML', 'NF-e XML')], max_length=20)),
                ('modo_comparacao', models.CharField(choices=[('COM_LOTE', 'Código + lote'), ('SEM_LOTE', 'Somente código')], default='COM_LOTE', max_length=20)),
                ('nome_arquivo', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aplicado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('PRONTA', 'Pronta para conferência'), ('APLICADA', 'Aplicada'), ('CANCELADA', 'Cancelada'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=20)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LinhaComparacaoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=500)),
                ('codigo', models.CharField(blank=True, default='', max_length=100)),
                ('lote', models.CharField(blank=True, default='', max_length=200)),
                ('nome_arquivo', models.CharField(blank=True, default='', max_length=500)),
                ('quantidade_sistema', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantidade_arquivo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unidade_sistema', models.CharField(blank=True, default='', max_length=50)),
                ('unidade_arquivo', models.CharField(blank=True, default='', max_length=50)),
                ('dados_arquivo', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IGUAL', 'Sistema = arquivo'), ('SALDO_DIVERGENTE', 'Saldo divergente'), ('UNIDADE_DIVERGENTE', 'Unidade divergente'), ('DADOS_DIVERGENTES', 'Dados divergentes'), ('SO_SISTEMA', 'Somente no sistema'), ('SO_ARQUIVO', 'Somente no arquivo'), ('AMBIGUO', 'Correspondência ambígua')], max_length=30)),
                ('acao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('MANTER_SISTEMA', 'Manter sistema'), ('USAR_ARQUIVO', 'Usar arquivo'), ('CRIAR_ITEM', 'Criar item'), ('IGNORAR', 'Ignorar')], default='PENDENTE', max_length=30)),
                ('aplicado', models.BooleanField(default=False)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='almoxarifado.importacaoinventario')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparacoes_inventario', to='almoxarifado.item')),
            ],
            options={
                'ordering': ['status', 'codigo', 'lote', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisparoRegraNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_evento', models.CharField(db_index=True, max_length=255)),
                ('destinatario', models.CharField(blank=True, default='', max_length=40)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('resposta', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disparos_regras', to='almoxarifado.item')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disparos', to='almoxarifado.regranotificacaoalmoxarifado')),
            ],
            options={
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['regra', 'item', 'chave_evento'], name='almoxarifad_regra_i_639172_idx')],
            },
        ),
    ]
