# Generated by Django 5.2 on 2026-09-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0022_regranotificacaoalmoxarifado_dadosvalidadeitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosvalidadeitem',
            options={'ordering': ['data_vencimento', 'item__nome']},
        ),
        migrations.AlterModelOptions(
            name='regranotificacaoalmoxarifado',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='disparoregranotificacao',
            name='almoxarifad_regra_i_639172_idx',
        ),
        migrations.AlterField(
            model_name='dadosvalidadeitem',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacaoinventario',
            name='status',
            field=models.CharField(choices=[('PROCESSANDO', 'Processando'), ('PRONTA', 'Pronta'), ('APLICADA', 'Aplicada'), ('CANCELADA', 'Cancelada'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='linhacomparacaoinventario',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almoxarifado.item'),
        ),
        migrations.AlterField(
            model_name='linhacomparacaoinventario',
            name='status',
            field=models.CharField(choices=[('IGUAL', 'Sistema = arquivo'), ('SALDO_DIVERGENTE', 'Saldo divergente'), ('UNIDADE_DIVERGENTE', 'Unidade divergente'), ('DADOS_DIVERGENTES', 'Dados divergentes'), ('SO_SISTEMA', 'Somente no sistema'), ('SO_ARQUIVO', 'Somente no arquivo'), ('AMBIGUO', 'Ambíguo')], max_length=30),
        ),
    ]
