# Generated by Django 5.2 on 2025-08-02 04:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoExibicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos_visiveis_produto', models.TextField(blank=True, default='', help_text='Campos do produto a serem exibidos na consulta, separados por vírgula.')),
                ('campos_visiveis_lote', models.TextField(blank=True, default='', help_text='Campos do lote a serem exibidos na consulta, separados por vírgula.')),
            ],
            options={
                'verbose_name_plural': 'Configurações de Exibição',
            },
        ),
        migrations.CreateModel(
            name='ProdutoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(default='', max_length=255, verbose_name='Descrição')),
                ('cultivar', models.CharField(blank=True, default='', max_length=100, verbose_name='Cultivar')),
                ('tecnologia', models.CharField(blank=True, default='', max_length=100, verbose_name='Tecnologia')),
                ('tratamento', models.CharField(blank=True, default='', max_length=100, verbose_name='Tratamento')),
                ('obtentor_mapa', models.CharField(blank=True, default='', max_length=100, verbose_name='Obtentor MAPA')),
                ('marca', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('embalagem', models.CharField(blank=True, default='', max_length=100, verbose_name='Embalagem')),
                ('tipo', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Produto (Cadastro)',
                'verbose_name_plural': 'Produtos (Cadastros)',
            },
        ),
        migrations.CreateModel(
            name='EstoqueLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código do Produto')),
                ('produto', models.CharField(blank=True, default='', max_length=255, verbose_name='Produto (Descrição)')),
                ('qnte', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Qnte')),
                ('pme', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='PME')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Volume')),
                ('filial', models.CharField(blank=True, default='', max_length=50, verbose_name='FILIAL')),
                ('az', models.CharField(blank=True, default='', max_length=50, verbose_name='Az')),
                ('rua', models.CharField(blank=True, default='', max_length=50, verbose_name='Rua')),
                ('bloco', models.CharField(blank=True, default='', max_length=50, verbose_name='Bloco')),
                ('quadra', models.CharField(blank=True, default='', max_length=50, verbose_name='Quadra')),
                ('lote_endereco', models.CharField(blank=True, default='', max_length=50, verbose_name='Lote Endereço')),
                ('categoria', models.CharField(blank=True, default='', max_length=100, verbose_name='Categoria')),
                ('peneira', models.CharField(blank=True, default='', max_length=100, verbose_name='Peneira')),
                ('embalagem', models.CharField(blank=True, default='', max_length=100, verbose_name='Embalagem')),
                ('quantsc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Quant SC')),
                ('quantbg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Quant Bg')),
                ('variedade', models.CharField(blank=True, default='', max_length=100, verbose_name='Variedade')),
                ('tipo', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo')),
                ('dtfabricacao', models.DateField(blank=True, null=True, verbose_name='Dt.Fabricação')),
                ('dtvalidade', models.DateField(blank=True, null=True, verbose_name='Dt.Validade')),
                ('tecnologia', models.CharField(blank=True, default='', max_length=100, verbose_name='Tecnologia')),
                ('tratamento', models.CharField(blank=True, default='', max_length=100, verbose_name='Tratamento')),
                ('obtentora', models.CharField(blank=True, default='', max_length=100, verbose_name='Obtentora')),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Umidade')),
                ('qntebloq', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Qnte Bloq.')),
                ('volumebloq', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Volume Bloq.')),
                ('um', models.CharField(blank=True, default='', max_length=50, verbose_name='Um')),
                ('motivo_bloq', models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo Bloq.')),
                ('lassg', models.CharField(blank=True, default='', max_length=100, verbose_name='Lassg')),
                ('cultura', models.CharField(blank=True, default='', max_length=100, verbose_name='Cultura')),
                ('obs_bloqueio', models.TextField(blank=True, default='', verbose_name='Obs_bloqueio')),
                ('numero_reserva', models.CharField(blank=True, default='', max_length=100, verbose_name='NUMERO_RESERVA')),
                ('quantidade_reserva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='QUANTIDADE_RESERVA')),
                ('germinacao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='GERMINACAO')),
                ('vigor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='VIGOR')),
                ('class_lote', models.CharField(blank=True, default='', max_length=100, verbose_name='CLASS_LOTE')),
                ('saldoliberado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Saldo_Liberado')),
                ('chave', models.CharField(blank=True, default='', max_length=255, verbose_name='CHAVE')),
                ('chave2', models.CharField(blank=True, default='', max_length=255, verbose_name='Chave2')),
                ('endereco', models.CharField(blank=True, default='', max_length=255, verbose_name='ENDEREÇO')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'unique_together': {('lote', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_buscado', models.CharField(max_length=255)),
                ('data_consulta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Consulta')),
                ('resultados_encontrados', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Consulta',
                'verbose_name_plural': 'Históricos de Consultas',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
