# Generated by Django 5.2 on 2025-11-19 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocultar_esgotados', models.BooleanField(default=False, verbose_name='Ocultar Lotes Esgotados')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peneira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('az', models.CharField(blank=True, max_length=10, null=True, verbose_name='AZ')),
                ('endereco', models.CharField(max_length=50)),
                ('entrada', models.IntegerField(default=0)),
                ('saida', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0, editable=False)),
                ('origem_destino', models.CharField(max_length=100, verbose_name='Origem/Destino')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('especie', models.CharField(default='SOJA', max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('embalagem', models.CharField(choices=[('BAG', 'Big Bag'), ('SC', 'Saco')], max_length=3)),
                ('peso_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (Kg)')),
                ('lote_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('peso_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sapp.categoria', verbose_name='CAT')),
                ('conferente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Conferente')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sapp.cultivar', verbose_name='Cultivar')),
                ('peneira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sapp.peneira', verbose_name='PN')),
                ('tratamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp.tratamento', verbose_name='Tratamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_ref', models.CharField(default='--', max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='sapp.estoque')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_acesso', models.BooleanField(default=True, verbose_name='Deve mudar senha?')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
