# Generated by Django 5.2 on 2025-07-27 22:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoExibicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração Padrão', max_length=100)),
                ('campos_visiveis_produto', models.TextField(default='cultivar,tecnologia,tratamento,descricao')),
                ('campos_visiveis_lote', models.TextField(default='lote,codigo,endereco,qnte,data_validade,saldo_liberado')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCadastro',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Código')),
                ('cultivar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cultivar')),
                ('tecnologia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tecnologia')),
                ('tratamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tratamento')),
                ('obtentor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obtentor')),
                ('mapa', models.CharField(blank=True, max_length=100, null=True, verbose_name='MAPA')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('embalagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Embalagem')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, verbose_name='Código')),
                ('lote', models.CharField(db_index=True, max_length=100, verbose_name='Lote')),
                ('qnte', models.FloatField(blank=True, null=True, verbose_name='Qnte')),
                ('pme', models.FloatField(blank=True, null=True, verbose_name='PME')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Volume')),
                ('quant_sc', models.FloatField(blank=True, null=True, verbose_name='Quant SC')),
                ('quant_bg', models.FloatField(blank=True, null=True, verbose_name='Quant Bg')),
                ('um', models.CharField(blank=True, max_length=50, null=True, verbose_name='Um')),
                ('saldo_liberado', models.FloatField(blank=True, null=True, verbose_name='Saldo Liberado')),
                ('filial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Filial')),
                ('az', models.CharField(blank=True, max_length=50, null=True, verbose_name='Az')),
                ('rua', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rua')),
                ('bloco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco')),
                ('quadra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quadra')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('produto_descricao_planilha', models.CharField(blank=True, max_length=255, null=True, verbose_name='Produto')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('peneira', models.CharField(blank=True, max_length=100, null=True, verbose_name='Peneira')),
                ('embalagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Embalagem')),
                ('variedade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedade')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('tecnologia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tecnologia')),
                ('tratamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tratamento')),
                ('obtentora', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obtentora')),
                ('cultura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultura')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Dt.Fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Dt.Validade')),
                ('umidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Umidade')),
                ('germinacao', models.IntegerField(blank=True, null=True, verbose_name='Germinação')),
                ('vigor', models.IntegerField(blank=True, null=True, verbose_name='Vigor')),
                ('class_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Class Lote')),
                ('qnte_bloq', models.FloatField(blank=True, null=True, verbose_name='Qnte Bloq')),
                ('volume_bloq', models.FloatField(blank=True, null=True, verbose_name='Volume Bloq.')),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Bloq.')),
                ('obs_bloqueio', models.TextField(blank=True, null=True, verbose_name='Obs_bloqueio')),
                ('numero_reserva', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero Reserva')),
                ('quantidade_reserva', models.FloatField(blank=True, null=True, verbose_name='Quantidade Reserva')),
                ('lassg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lassg')),
                ('chave', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave')),
                ('chave2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave2')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'unique_together': {('lote', 'endereco', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_buscado', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultados_encontrados', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Consulta',
                'verbose_name_plural': 'Históricos de Consulta',
                'ordering': ['-data_hora'],
            },
        ),
    ]
