# Generated by Django 5.2 on 2025-12-03 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='az',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sapp.categoria'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='conferente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='cultivar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sapp.cultivar'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='embalagem',
            field=models.CharField(choices=[('SC', 'Saco'), ('BAG', 'Big Bag')], default='BAG', max_length=10),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='endereco',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='origem_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='peneira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sapp.peneira'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='peso_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sapp.tratamento'),
        ),
    ]
