# Generated by Django 5.2 on 2025-12-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_alter_estoque_az_alter_estoque_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_ultima_movimentacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='data_ultima_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ESGOTADO', 'Esgotado'), ('INATIVO', 'Inativo'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20),
        ),
    ]
