# Generated by Django 5.2 on 2025-12-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0003_estoque_data_ultima_movimentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacao',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='historico_fotos/'),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='motorista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='numero_carga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
