# Generated by Django 5.2 on 2025-12-17 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0004_historicomovimentacao_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='historico_fotos/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='sapp.historicomovimentacao')),
            ],
        ),
    ]
