# Generated by Django 5.2 on 2025-12-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0005_fotomovimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicomovimentacao',
            name='foto',
        ),
    ]
