# Generated by Django 5.2 on 2025-12-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0006_remove_historicomovimentacao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacao',
            name='ordem_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicomovimentacao',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
