# Generated by Django 5.2 on 2025-12-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0007_historicomovimentacao_ordem_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='lote_anterior',
        ),
        migrations.AddField(
            model_name='estoque',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente/Dono do Bag'),
        ),
    ]
