# Generated by Django 5.2 on 2025-12-23 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0008_remove_estoque_lote_anterior_estoque_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpenhoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estoque',
            name='az',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cliente/Dono do Bag'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='observacao',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='origem_destino',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo_movimentacao', models.CharField(choices=[('EXPEDICAO', 'Expedição'), ('TRANSFERENCIA', 'Transferência'), ('EDICAO', 'Edição'), ('ENTRADA', 'Entrada')], default='EXPEDICAO', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('numero_carga', models.CharField(blank=True, max_length=50, null=True)),
                ('motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sapp.empenhostatus')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('endereco_origem', models.CharField(max_length=20)),
                ('endereco_destino', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.CharField(max_length=50)),
                ('cultivar', models.CharField(max_length=100)),
                ('peneira', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('saldo_anterior', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sapp.empenho')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empenhos', to='sapp.estoque')),
            ],
            options={
                'ordering': ['-data_criacao'],
                'unique_together': {('empenho', 'estoque')},
            },
        ),
    ]
