# Generated by Django 5.2 on 2025-12-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0010_especie_alter_estoque_especie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=50, unique=True, verbose_name='Código do Endereço')),
                ('pos_x', models.IntegerField(default=0, verbose_name='Posição X (px)')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Posição Y (px)')),
                ('largura', models.IntegerField(default=100, verbose_name='Largura (px)')),
                ('altura', models.IntegerField(default=60, verbose_name='Altura (px)')),
                ('cor_padrao', models.CharField(default='#CCCCCC', max_length=7, verbose_name='Cor Padrão (vazio)')),
                ('cor_positivo', models.CharField(default='#10b981', max_length=7, verbose_name='Cor com Saldo')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mapeamento de Endereço',
            },
        ),
    ]
