# Generated by Django 5.2 on 2025-12-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0011_mapeamentoendereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeamentoendereco',
            name='armazem',
            field=models.IntegerField(default=1, verbose_name='Número do Armazém'),
        ),
    ]
