# Generated by Django 5.2 on 2025-12-28 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0012_mapeamentoendereco_armazem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmazemLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número do Armazém')),
                ('nome', models.CharField(default='', max_length=100)),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='mapa_armazens/', verbose_name='Imagem de Fundo (Planta Baixa)')),
                ('largura_canvas', models.IntegerField(default=1000)),
                ('altura_canvas', models.IntegerField(default=600)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Layout do Armazém',
                'verbose_name_plural': 'Layouts dos Armazéns',
            },
        ),
        migrations.CreateModel(
            name='ElementoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RETANGULO', 'Retângulo/Endereço'), ('LINHA', 'Linha'), ('TEXTO', 'Texto')], max_length=20)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=100)),
                ('altura', models.IntegerField(default=60)),
                ('cor_preenchimento', models.CharField(default='#CCCCCC', max_length=7)),
                ('cor_borda', models.CharField(default='#000000', max_length=7)),
                ('espessura_borda', models.IntegerField(default=2)),
                ('conteudo_texto', models.TextField(blank=True, null=True)),
                ('fonte_nome', models.CharField(default='Arial', max_length=100)),
                ('fonte_tamanho', models.IntegerField(default=14)),
                ('texto_negrito', models.BooleanField(default=False)),
                ('texto_italico', models.BooleanField(default=False)),
                ('texto_direcao', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20)),
                ('linha_tipo', models.CharField(choices=[('solida', 'Sólida'), ('tracejada', 'Tracejada'), ('pontilhada', 'Pontilhada')], default='solida', max_length=20)),
                ('identificador', models.CharField(blank=True, max_length=50, null=True)),
                ('ordem_z', models.IntegerField(default=1)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='sapp.armazemlayout')),
            ],
            options={
                'verbose_name': 'Elemento do Mapa',
                'verbose_name_plural': 'Elementos do Mapa',
                'ordering': ['armazem', 'ordem_z'],
            },
        ),
    ]
