# Generated by Django 5.2 on 2025-12-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0013_armazemlayout_elementomapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapeamentoEndereco',
        ),
        migrations.AddField(
            model_name='elementomapa',
            name='rotacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armazemlayout',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='mapa_armazens/'),
        ),
        migrations.AlterField(
            model_name='elementomapa',
            name='cor_borda',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='elementomapa',
            name='cor_preenchimento',
            field=models.CharField(default='#CCCCCC', max_length=20),
        ),
    ]
