# Generated by Django 5.2 on 2026-01-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0014_delete_mapeamentoendereco_elementomapa_rotacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacao',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
