# Generated by Django 5.2 on 2026-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0016_alinhar_historico_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomovimentacao',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
