# Generated by Django 5.2 on 2026-01-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0017_alter_historicomovimentacao_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotomovimentacao',
            name='legenda',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fotomovimentacao',
            name='arquivo',
            field=models.FileField(upload_to='fotos_movimentacao/'),
        ),
    ]
