# Generated by Django 5.2 on 2026-01-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0018_fotomovimentacao_legenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotomovimentacao',
            name='legenda',
        ),
        migrations.AlterField(
            model_name='fotomovimentacao',
            name='arquivo',
            field=models.ImageField(upload_to='historico_fotos/%Y/%m/'),
        ),
    ]
