# Generated by Django 5.2 on 2026-02-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0019_remove_fotomovimentacao_legenda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp.categoria', verbose_name='Categoria')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sapp.cultivar', verbose_name='Cultivar')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp.especie', verbose_name='Espécie')),
                ('peneira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp.peneira', verbose_name='Peneira')),
                ('tratamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp.tratamento', verbose_name='Tratamento')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['cultivar__nome', 'codigo'],
            },
        ),
    ]
