# Generated by Django 5.2 on 2026-02-20 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0020_produto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='status_sistemico',
            field=models.CharField(choices=[('ok', 'OK - Tudo certo (Verde)'), ('parcial', 'Parcial - Divergência (Amarelo)'), ('critico', 'Crítico - Sem saldo real (Vermelho)')], default='critico', max_length=20, verbose_name='Status Sistêmico'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='status_sistemico_alterado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='status_sistemico_alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_sistemico_alteracoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Gráfico')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_grafico', models.CharField(choices=[('bar', 'Barras Verticais'), ('bar_horizontal', 'Barras Horizontais'), ('pie', 'Pizza'), ('doughnut', 'Rosca'), ('line', 'Linha'), ('area', 'Área'), ('radar', 'Radar'), ('polar', 'Polar'), ('scatter', 'Dispersão'), ('bubble', 'Bolhas')], default='bar', max_length=20, verbose_name='Tipo de Gráfico')),
                ('largura', models.IntegerField(default=6, help_text='1-12 colunas do Bootstrap', verbose_name='Largura (colunas)')),
                ('altura', models.IntegerField(default=400, verbose_name='Altura (px)')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('cor_principal', models.CharField(default='#198754', max_length=20, verbose_name='Cor Principal')),
                ('mostrar_legenda', models.BooleanField(default=True, verbose_name='Mostrar Legenda')),
                ('mostrar_valores', models.BooleanField(default=True, verbose_name='Mostrar Valores')),
                ('mostrar_percentual', models.BooleanField(default=False, verbose_name='Mostrar %')),
                ('agrupamento_principal', models.CharField(choices=[('cultivar', 'Cultivar'), ('peneira', 'Peneira'), ('especie', 'Espécie'), ('categoria', 'Categoria'), ('tratamento', 'Tratamento'), ('embalagem', 'Embalagem'), ('cliente', 'Cliente'), ('empresa', 'Empresa'), ('az', 'Armazém (AZ)'), ('endereco', 'Endereço'), ('lote_prefix', 'Prefixo do Lote'), ('lote_sufix', 'Sufixo do Lote'), ('lote_pattern', 'Padrão no Lote'), ('conferente', 'Conferente'), ('mes_entrada', 'Mês de Entrada'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('ano', 'Ano')], max_length=30, verbose_name='Agrupar por')),
                ('agrupamento_secundario', models.CharField(blank=True, choices=[('cultivar', 'Cultivar'), ('peneira', 'Peneira'), ('especie', 'Espécie'), ('categoria', 'Categoria'), ('tratamento', 'Tratamento'), ('embalagem', 'Embalagem'), ('cliente', 'Cliente'), ('empresa', 'Empresa'), ('az', 'Armazém (AZ)'), ('endereco', 'Endereço'), ('lote_prefix', 'Prefixo do Lote'), ('lote_sufix', 'Sufixo do Lote'), ('lote_pattern', 'Padrão no Lote'), ('conferente', 'Conferente'), ('mes_entrada', 'Mês de Entrada'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('ano', 'Ano')], max_length=30, null=True, verbose_name='Agrupar por (2º nível)')),
                ('metrica', models.CharField(choices=[('saldo', 'Saldo (Quantidade)'), ('entrada', 'Total de Entradas'), ('saida', 'Total de Saídas'), ('peso_total', 'Peso Total (kg)'), ('qtd_lotes', 'Quantidade de Lotes'), ('media_peso', 'Média de Peso por Lote'), ('taxa_giro', 'Taxa de Giro'), ('dias_estoque', 'Dias em Estoque')], default='saldo', max_length=20, verbose_name='Métrica')),
                ('ordenacao', models.CharField(choices=[('valor_desc', 'Maior para Menor'), ('valor_asc', 'Menor para Maior'), ('nome_asc', 'Nome (A-Z)'), ('nome_desc', 'Nome (Z-A)'), ('data_desc', 'Mais Recente'), ('data_asc', 'Mais Antigo')], default='valor_desc', max_length=20, verbose_name='Ordenar por')),
                ('limite_itens', models.IntegerField(default=10, help_text='0 = sem limite', verbose_name='Limite de Itens')),
                ('filtros_json', models.TextField(blank=True, help_text='Configuração dos filtros em JSON', verbose_name='Filtros')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Dashboard',
                'verbose_name_plural': 'Configurações de Dashboards',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
