# Generated by Django 5.2 on 2026-02-21 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0021_estoque_status_sistemico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardconfig',
            options={'verbose_name': 'Configuração do Dashboard', 'verbose_name_plural': 'Configurações do Dashboard'},
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='agrupamento_principal',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='agrupamento_secundario',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='cor_principal',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='filtros_json',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='limite_itens',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='metrica',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='mostrar_legenda',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='mostrar_percentual',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='mostrar_valores',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='ordenacao',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='tipo_grafico',
        ),
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='titulo',
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='armazem_metrica',
            field=models.CharField(choices=[('volume', 'Volume (SC)'), ('lotes', 'Quantidade de Lotes'), ('peso', 'Peso Total (kg)')], default='volume', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='armazem_ordem',
            field=models.CharField(choices=[('valor_desc', 'Maior Valor'), ('valor_asc', 'Menor Valor'), ('nome_asc', 'Nome (A-Z)'), ('nome_desc', 'Nome (Z-A)')], default='nome_asc', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='armazem_tipo',
            field=models.CharField(choices=[('doughnut', 'Rosca (Doughnut)'), ('pie', 'Pizza (Pie)'), ('bar', 'Barras'), ('horizontalBar', 'Barras Horizontais'), ('line', 'Linha'), ('area', 'Área')], default='bar', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='auto_refresh',
            field=models.IntegerField(default=0, help_text='Tempo em segundos (0 = desativado)'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='cultivar_agrupar_outros',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='cultivar_ordem',
            field=models.CharField(choices=[('valor_desc', 'Maior Valor'), ('valor_asc', 'Menor Valor'), ('nome_asc', 'Nome (A-Z)'), ('nome_desc', 'Nome (Z-A)')], default='valor_desc', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='cultivar_qtd',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='cultivar_tipo',
            field=models.CharField(choices=[('doughnut', 'Rosca (Doughnut)'), ('pie', 'Pizza (Pie)'), ('bar', 'Barras'), ('horizontalBar', 'Barras Horizontais'), ('line', 'Linha'), ('area', 'Área')], default='doughnut', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='cultivar_zerados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='filtro_armazem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='filtro_cultivar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='filtro_peneira',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='filtro_periodo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='layout_config',
            field=models.TextField(default='{}', help_text='Configuração de layout em JSON'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='mostrar_legendas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='mostrar_percentuais',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='peneira_ordem',
            field=models.CharField(choices=[('valor_desc', 'Maior Valor'), ('valor_asc', 'Menor Valor'), ('nome_asc', 'Nome (A-Z)'), ('nome_desc', 'Nome (Z-A)')], default='valor_desc', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='peneira_qtd',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='peneira_tipo',
            field=models.CharField(choices=[('doughnut', 'Rosca (Doughnut)'), ('pie', 'Pizza (Pie)'), ('bar', 'Barras'), ('horizontalBar', 'Barras Horizontais'), ('line', 'Linha'), ('area', 'Área')], default='pie', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='tema_cores',
            field=models.CharField(choices=[('default', 'Padrão (Verde)'), ('modern', 'Moderno (Azul)'), ('pastel', 'Pastel'), ('dark', 'Escuro')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='tendencia_agrupamento',
            field=models.CharField(choices=[('day', 'Por Dia'), ('week', 'Por Semana'), ('month', 'Por Mês')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='tendencia_periodo',
            field=models.IntegerField(choices=[(7, 'Últimos 7 dias'), (15, 'Últimos 15 dias'), (30, 'Últimos 30 dias'), (90, 'Últimos 90 dias')], default=7),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='tendencia_saidas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='tendencia_transferencias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='unidade_padrao',
            field=models.CharField(choices=[('sc', 'Sacas (SC)'), ('bags', 'Bags'), ('kg', 'Quilogramas (kg)')], default='sc', max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DashboardFiltroSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('filtros', models.TextField(help_text='Filtros em JSON')),
                ('compartilhado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_salvos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro Salvo',
                'verbose_name_plural': 'Filtros Salvos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('grafico', 'Gráfico'), ('tabela', 'Tabela'), ('kpi', 'Indicador KPI'), ('lista', 'Lista')], max_length=20)),
                ('origem_dados', models.CharField(choices=[('cultivares', 'Top Cultivares'), ('peneiras', 'Distribuição por Peneira'), ('armazens', 'Ocupação por Armazém'), ('tendencia', 'Tendência de Movimentação'), ('estoque_resumo', 'Resumo do Estoque'), ('ultimas_mov', 'Últimas Movimentações'), ('clientes_top', 'Top Clientes'), ('produtos_top', 'Top Produtos')], max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=6)),
                ('altura', models.IntegerField(default=4)),
                ('config', models.TextField(default='{}', help_text='Configurações específicas do widget em JSON')),
                ('ativo', models.BooleanField(default=True)),
                ('visivel_para_todos', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets_criados', to=settings.AUTH_USER_MODEL)),
                ('usuarios_permitidos', models.ManyToManyField(blank=True, related_name='widgets_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget do Dashboard',
                'verbose_name_plural': 'Widgets do Dashboard',
                'ordering': ['ordem', 'pos_y', 'pos_x'],
            },
        ),
    ]
