# Generated by Django 5.2 on 2026-02-21 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0022_alter_dashboardconfig_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardconfig',
            unique_together={('criado_por',)},
        ),
    ]
