# Generated by Django 5.2 on 2026-02-27 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0023_alter_dashboardconfig_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Tamanho recomendado: 200x100px. Faça upload pelo Django Admin.', null=True, upload_to='logos/', verbose_name='Logo da Empresa')),
                ('nome_empresa', models.CharField(default='GRUPO CONCEITO', max_length=100, verbose_name='Nome da Empresa')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas uma configuração deve estar ativa', verbose_name='Ativo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração da Logo',
                'verbose_name_plural': 'Configurações da Logo',
            },
        ),
    ]
