# Generated by Django 5.2 on 2026-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0024_configuracaologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='ultimo_lote_linha',
            field=models.BooleanField(default=False, verbose_name='Último Lote da Linha'),
        ),
    ]
