# Generated by Django 5.2 on 2026-03-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0026_armazem_linha_origemdestino_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='sapp.rua'),
        ),
        migrations.AlterField(
            model_name='linha',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rua',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='linha',
            unique_together={('nome', 'rua')},
        ),
        migrations.AlterUniqueTogether(
            name='rua',
            unique_together={('nome', 'armazem')},
        ),
    ]
