# Generated by Django 5.2 on 2026-04-04 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0027_linha_rua_alter_linha_nome_alter_rua_nome_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rua',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rua',
            name='armazem',
        ),
        migrations.AlterField(
            model_name='configuracaologo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='configuracaologo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Empresa'),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='auto_refresh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='layout_config',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='dashboardfiltrosalvo',
            name='filtros',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='config',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Endereço completo')),
                ('rua', models.CharField(max_length=10, verbose_name='Rua')),
                ('linha', models.CharField(blank=True, max_length=10, null=True, verbose_name='Linha')),
                ('posicao', models.IntegerField(blank=True, null=True, verbose_name='Posição')),
                ('tipo', models.CharField(choices=[('POSICAO', 'Posição específica'), ('LINHA', 'Linha inteira'), ('GERAL', 'Área geral'), ('EXTERNO', 'Externo')], default='POSICAO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='sapp.armazem')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['codigo'],
            },
        ),
        migrations.DeleteModel(
            name='Linha',
        ),
        migrations.DeleteModel(
            name='Rua',
        ),
    ]
