# Generated by Django 5.2 on 2026-04-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0028_alter_rua_unique_together_remove_rua_armazem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['armazem__nome', 'codigo'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='linha',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='armazem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='sapp.armazem'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Endereço completo'),
        ),
    ]
