# Generated by Django 5.2 on 2026-05-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0029_alter_endereco_options_remove_endereco_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['cultivar__nome', 'codigo'], 'permissions': [('pode_ver_estoque', 'Pode visualizar estoque'), ('pode_movimentar_estoque', 'Pode movimentar estoque'), ('pode_ver_dashboard', 'Pode acessar o dashboard'), ('pode_ver_almoxarifado', 'Pode visualizar almoxarifado'), ('pode_gerenciar_almoxarifado', 'Pode gerenciar almoxarifado'), ('pode_ver_empenhos', 'Pode visualizar empenhos'), ('pode_criar_empenhos', 'Pode criar empenhos'), ('pode_ver_mapa', 'Pode acessar mapa canvas'), ('pode_gerenciar_usuarios', 'Pode gerenciar usuários'), ('pode_configuracoes', 'Pode alterar configurações')], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
