# Generated by Django 5.2 on 2026-07-08 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0030_alter_produto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='status_sistemico_observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StatusSistemico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Status')),
                ('cor', models.CharField(default='#6c757d', max_length=20, verbose_name='Cor (Hex)')),
                ('legenda', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda/Descrição')),
                ('icone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ícone (emoji)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('e_padrao', models.BooleanField(default=False, verbose_name='É Status Padrão')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Sistêmico',
                'verbose_name_plural': 'Status Sistêmicos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatusSistemico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='sapp.estoque')),
                ('status_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_anterior', to='sapp.statussistemico')),
                ('status_novo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_novo', to='sapp.statussistemico')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.AlterField(
            model_name='estoque',
            name='status_sistemico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoques', to='sapp.statussistemico', verbose_name='Status Sistêmico'),
        ),
    ]
