# Generated by Django 5.2 on 2026-07-23 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0031_estoque_status_sistemico_observacao_statussistemico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoItemEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_empenho_id_original', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID do ItemEmpenho removido após o processamento.', null=True)),
                ('lote', models.CharField(db_index=True, max_length=100)),
                ('produto', models.CharField(blank=True, default='', max_length=255)),
                ('cultivar', models.CharField(blank=True, default='', max_length=255)),
                ('peneira', models.CharField(blank=True, default='', max_length=100)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('tratamento', models.CharField(blank=True, default='', max_length=255)),
                ('especie', models.CharField(blank=True, default='', max_length=100)),
                ('embalagem', models.CharField(blank=True, default='', max_length=100)),
                ('empresa', models.CharField(blank=True, default='', max_length=255)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('endereco_origem', models.CharField(blank=True, default='', max_length=100)),
                ('endereco_destino', models.CharField(blank=True, default='', max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferência'), ('expedicao', 'Expedição')], db_index=True, max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('numero_carga', models.CharField(blank=True, default='', max_length=100)),
                ('placa', models.CharField(blank=True, default='', max_length=20)),
                ('processado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_itens', to='sapp.empenho', verbose_name='Card de empenho')),
                ('estoque_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_itens_destino', to='sapp.estoque')),
                ('estoque_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_itens_origem', to='sapp.estoque')),
                ('processado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_itens_empenhados_processados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de item empenhado',
                'verbose_name_plural': 'Históricos de itens empenhados',
                'ordering': ['-processado_em', '-id'],
                'indexes': [models.Index(fields=['empenho', '-processado_em'], name='hist_emp_data_idx'), models.Index(fields=['estoque_origem', '-processado_em'], name='hist_origem_data_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='hist_item_quantidade_maior_zero')],
            },
        ),
    ]
