# Generated by Django 5.2 on 2026-07-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0032_historicoitemempenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='empenhado',
            field=models.IntegerField(default=0, verbose_name='Quantidade Empenhada'),
        ),
    ]
