# Generated by Django 5.2 on 2026-07-24 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0033_estoque_empenhado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Coluna')),
                ('cor', models.CharField(default='#6c757d', max_length=20, verbose_name='Cor')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Coluna Kanban',
                'verbose_name_plural': 'Colunas Kanban',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som_ativo', models.BooleanField(default=True, verbose_name='Som Ativo')),
                ('volume', models.IntegerField(default=50, verbose_name='Volume (0-100)')),
                ('intervalo_atualizacao', models.IntegerField(default=30, verbose_name='Intervalo (segundos)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração de Atualização',
                'verbose_name_plural': 'Configurações de Atualização',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Card')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('unidade_controle', models.CharField(choices=[('EMBALAGEM', 'Embalagem'), ('QUILOGRAMA', 'Quilograma')], default='EMBALAGEM', max_length=20, verbose_name='Unidade de Controle')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Solicitada')),
                ('quantidade_empenhada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Empenhada')),
                ('quantidade_movimentada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Movimentada')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(default='AGUARDANDO_EMPENHO', max_length=30, verbose_name='Status da Solicitação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp.armazem', verbose_name='Armazém')),
                ('coluna_kanban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='sapp.colunakanban', verbose_name='Coluna do Kanban')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário criador')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp.especie', verbose_name='Espécie')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-data_criacao'],
                'permissions': [('pode_criar_solicitacao', 'Pode criar solicitação'), ('pode_empenhar_solicitacao', 'Pode empenhar itens em solicitação'), ('pode_movimentar_solicitacao', 'Pode transferir/expedir solicitação'), ('pode_cancelar_solicitacao', 'Pode cancelar solicitação')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'criou a solicitação'), ('EMPENHO', 'empenhou'), ('TRANSFERENCIA', 'transferiu'), ('EXPEDICAO', 'expediu'), ('CANCELAMENTO', 'cancelou'), ('MOVIMENTACAO_KANBAN', 'moveu o card'), ('REMOCAO_ITEM', 'removeu item'), ('CONCLUSAO', 'concluiu')], max_length=20, verbose_name='Ação')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('unidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade')),
                ('coluna_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coluna Anterior')),
                ('coluna_nova', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nova Coluna')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='sapp.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Histórico do Card',
                'verbose_name_plural': 'Históricos dos Cards',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegraWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CRIACAO', 'Solicitação Criada'), ('PRIMEIRO_EMPENHO', 'Primeiro Item Empenhado'), ('EMPENHO_PARCIAL', 'Empenho Parcial'), ('EMPENHO_COMPLETO', 'Volume Totalmente Empenhado'), ('PRIMEIRA_MOVIMENTACAO', 'Primeira Movimentação'), ('MOVIMENTACAO_PARCIAL', 'Movimentação Parcial'), ('TRANSFERENCIA_COMPLETA', 'Transferência Completa'), ('EXPEDICAO_COMPLETA', 'Expedição Completa'), ('CONCLUSAO', 'Conclusão'), ('CANCELAMENTO', 'Cancelamento'), ('MOVIMENTACAO_MANUAL', 'Movimentação Manual')], max_length=30, verbose_name='Evento')),
                ('status_resultante', models.CharField(max_length=30, verbose_name='Status Resultante')),
                ('movimentacao_automatica', models.BooleanField(default=True, verbose_name='Movimentação Automática')),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='sapp.colunakanban', verbose_name='Coluna')),
            ],
            options={
                'verbose_name': 'Regra de Workflow',
                'verbose_name_plural': 'Regras de Workflow',
                'unique_together': {('coluna', 'evento')},
            },
        ),
    ]
