# Generated by Django 5.2 on 2026-07-30 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0034_colunakanban_configuracaoatualizacao_solicitacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empenhos', to='sapp.solicitacao', verbose_name='Solicitação vinculada'),
        ),
        migrations.AddIndex(
            model_name='empenho',
            index=models.Index(fields=['solicitacao', 'status'], name='emp_sol_status_idx'),
        ),
    ]
