# Generated by Django 5.2 on 2026-08-06 02:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0035_empenho_solicitacao_empenho_emp_sol_status_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Texto da tag')),
                ('icone', models.CharField(blank=True, default='', help_text='Classe Font Awesome. Ex.: fas fa-print', max_length=50, verbose_name='Ícone')),
                ('cor', models.CharField(default='#2f8f4e', max_length=20, verbose_name='Cor de fundo')),
                ('cor_texto', models.CharField(default='#ffffff', max_length=20, verbose_name='Cor do texto')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag do Kanban',
                'verbose_name_plural': 'Tags do Kanban',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-data_criacao', '-id'], 'permissions': [('pode_criar_solicitacao', 'Pode criar solicitação'), ('pode_empenhar_solicitacao', 'Pode empenhar itens em solicitação'), ('pode_movimentar_solicitacao', 'Pode transferir/expedir solicitação'), ('pode_cancelar_solicitacao', 'Pode cancelar solicitação')], 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/hora da finalização'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='destino',
            field=models.CharField(blank=True, default='', help_text='Destino da solicitação, transferência ou expedição.', max_length=255, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/hora da criação'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='quantidade_empenhada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantidade Empenhada'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='quantidade_movimentada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantidade Movimentada'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='quantidade_solicitada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantidade Solicitada'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_EMPENHO', 'Aguardando empenho'), ('EMPENHO_PARCIAL', 'Empenho parcial'), ('EMPENHO_COMPLETO', 'Empenho completo'), ('MOVIMENTACAO_PARCIAL', 'Movimentação parcial'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='AGUARDANDO_EMPENHO', max_length=30, verbose_name='Status da Solicitação'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tags_kanban',
            field=models.ManyToManyField(blank=True, related_name='solicitacoes', to='sapp.tagkanban', verbose_name='Tags do Kanban'),
        ),
    ]
