# Generated by Django 5.2 on 2026-08-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0036_tagkanban_alter_solicitacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoitemempenho',
            name='az_origem',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicoitemempenho',
            name='conferente',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicoitemempenho',
            name='observacao_origem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicoitemempenho',
            name='peso_unitario',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='historicoitemempenho',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='az_origem',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Armazém/AZ no momento do empenho'),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='cliente_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='conferente_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='embalagem_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='empresa_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='especie_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='observacao_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='peso_unitario_snapshot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='produto_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemempenho',
            name='tratamento_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemempenho',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemempenho',
            name='cultivar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemempenho',
            name='endereco_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemempenho',
            name='endereco_origem',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemempenho',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemempenho',
            name='peneira',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
