# Generated by Django 5.1.2 on 2024-10-27 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_customuser_tipo_revenda_customuser_dono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dono',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clientes.servico'),
        ),
    ]
