# Generated by Django 5.1.2 on 2024-10-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_customuser_dono_alter_customuser_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL),
        ),
    ]
