# Generated by Django 5.1.2 on 2024-10-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_customuser_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='senha_leitura',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
