# Generated by Django 5.1.2 on 2024-10-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_customuser_senha_leitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
