# Generated by Django 5.1.2 on 2024-10-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_customuser_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='senha_leitura',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='clientes.tag'),
        ),
    ]
