# Generated by Django 5.1.2 on 2024-10-28 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_tag_remove_customuser_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='senha_leitura',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
