# Generated by Django 5.1.2 on 2024-10-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_tag_name_tag_descricao_tag_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pix_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pix_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pix_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
