# Generated by Django 5.1.2 on 2024-10-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_customuser_pix_code_customuser_pix_code_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
