# Generated by Django 5.1.2 on 2024-10-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='horario_envio',
            new_name='data_envio',
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='destinatario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='conteudo_substituido',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='resposta_api',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='status_envio',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='numero',
            field=models.CharField(blank=True, default='000000000', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
            preserve_default=False,
        ),
    ]
