# Generated by Django 5.1.2 on 2024-11-02 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_rename_horario_envio_mensagem_data_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antes_vencimento', models.IntegerField(default=3)),
                ('enviar_no_dia_vencimento', models.BooleanField(default=True)),
                ('enviar_apos_vencimento', models.BooleanField(default=True)),
                ('hora_execucao', models.TimeField(default=django.utils.timezone.now)),
                ('excecoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
