# Generated by Django 5.1.2 on 2024-11-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_configuracaomensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='excecoes',
        ),
        migrations.AddField(
            model_name='configuracaomensagem',
            name='mensagem_apos_vencimento',
            field=models.TextField(blank=True, default='Olá {nome}, seu plano {plano} venceu ontem. Renove para continuar com os serviços.', null=True),
        ),
        migrations.AddField(
            model_name='configuracaomensagem',
            name='mensagem_bem_vindo',
            field=models.TextField(blank=True, default='Bem-vindo, {nome}! Seu plano {plano} está ativo.', null=True),
        ),
        migrations.AddField(
            model_name='configuracaomensagem',
            name='mensagem_confirmacao_pagamento',
            field=models.TextField(blank=True, default='Olá {nome}, seu pagamento foi confirmado!', null=True),
        ),
        migrations.AddField(
            model_name='configuracaomensagem',
            name='mensagem_dias_antes_vencimento',
            field=models.TextField(blank=True, default='Olá {nome}, seu plano {plano} vence em {dias_antes_vencimento} dias. Não deixe de renovar!', null=True),
        ),
        migrations.AddField(
            model_name='configuracaomensagem',
            name='mensagem_no_dia_vencimento',
            field=models.TextField(blank=True, default='Olá {nome}, seu plano {plano} vence hoje!', null=True),
        ),
    ]
