# Generated by Django 5.1.2 on 2024-11-02 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_remove_configuracaomensagem_excecoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='enviar_apos_vencimento',
        ),
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='enviar_no_dia_vencimento',
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='dias_antes_vencimento',
            field=models.PositiveIntegerField(default=3, help_text='Número de dias antes do vencimento para enviar a mensagem.'),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='hora_execucao',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Hora em que as mensagens automáticas serão enviadas diariamente.'),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_apos_vencimento',
            field=models.TextField(blank=True, help_text='Mensagem enviada no dia após o vencimento.', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_bem_vindo',
            field=models.TextField(blank=True, help_text='Mensagem enviada ao cadastrar um novo cliente.', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_confirmacao_pagamento',
            field=models.TextField(blank=True, help_text='Mensagem enviada ao confirmar pagamento.', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_dias_antes_vencimento',
            field=models.TextField(blank=True, help_text='Mensagem enviada alguns dias antes do vencimento.', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_no_dia_vencimento',
            field=models.TextField(blank=True, help_text='Mensagem enviada no dia do vencimento.', null=True),
        ),
    ]
