# Generated by Django 5.1.2 on 2024-11-03 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_configuracaomensagem_enviar_apos_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='dias_antes_vencimento',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='hora_execucao',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_apos_vencimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_bem_vindo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_confirmacao_pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_dias_antes_vencimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='mensagem_no_dia_vencimento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
