# Generated by Django 5.1.2 on 2024-11-09 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_message_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_access_token', models.CharField(max_length=255)),
                ('api_telegram', models.CharField(max_length=255)),
                ('token_telegram', models.CharField(max_length=255)),
                ('chave_telegram', models.CharField(max_length=255)),
                ('numero_celular', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('api_whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('token_whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_envio_mensagens', models.TimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
