# Generated by Django 5.1.2 on 2024-11-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_configuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
