# Generated by Django 5.1.2 on 2024-11-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_alter_configuracao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='api_telegram',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='chave_telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='mercado_pago_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='token_telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
