# Generated by Django 5.1.2 on 2024-11-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_remove_configuracao_api_telegram_configuracao_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='hora_execucao',
        ),
    ]
