# Generated by Django 5.1.2 on 2024-11-11 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_remove_configuracaomensagem_hora_execucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagens', models.ImageField(blank=True, null=True, upload_to='atualizacoes/')),
                ('resolucao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
