# Generated by Django 5.1.2 on 2024-11-11 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atualizacao',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='atualizacao',
            name='resolucao',
        ),
        migrations.AddField(
            model_name='atualizacao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('novidades', 'Novidades'), ('correcao_bugs', 'Correção de Bugs')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atualizacao',
            name='versao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atualizacao',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='atualizacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atualizacao',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
