# Generated by Django 5.1.2 on 2024-11-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_remove_atualizacao_imagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='atualizacoes/'),
        ),
    ]
