# Generated by Django 5.1.2 on 2024-12-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_userinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='api_whatsapp',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='token_whatsapp',
        ),
    ]
