# Generated by Django 5.1.2 on 2024-12-04 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_remove_configuracao_api_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaomensagem',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
