# Generated by Django 5.1.2 on 2025-01-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_configuracaomensagem_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='custos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
