# Generated by Django 5.1.2 on 2025-03-01 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0032_servico_custos_alter_servico_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='dias_antes_vencimento',
        ),
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='mensagem_apos_vencimento',
        ),
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='mensagem_bem_vindo',
        ),
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='mensagem_confirmacao_pagamento',
        ),
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='mensagem_dias_antes_vencimento',
        ),
        migrations.RemoveField(
            model_name='configuracaomensagem',
            name='mensagem_no_dia_vencimento',
        ),
        migrations.CreateModel(
            name='MensagemConfigurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio_dias', models.IntegerField(help_text='Dias antes ou após o vencimento (ex: -1 para vencido, 5 para antes)')),
                ('mensagem_texto', models.TextField()),
                ('horario_envio', models.TimeField(default=django.utils.timezone.now)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='clientes.configuracaomensagem')),
            ],
        ),
    ]
