# Generated by Django 5.1.2 on 2025-03-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0033_remove_configuracaomensagem_dias_antes_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemconfigurada',
            name='horario_envio',
            field=models.TimeField(),
        ),
    ]
