# Generated by Django 5.1.2 on 2025-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0034_alter_mensagemconfigurada_horario_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='userinstance',
            name='instance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
