# Generated by Django 5.1.2 on 2025-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0035_remove_userinstance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofinanceiro',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
