# Generated by Django 5.1.2 on 2025-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0036_relatoriofinanceiro_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ajuste_recorrente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
