# Generated by Django 5.1.2 on 2025-04-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0037_customuser_ajuste_recorrente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ajuste_recorrente',
        ),
    ]
