# Generated by Django 5.1.2 on 2025-04-17 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0038_remove_customuser_ajuste_recorrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Tutorial')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('video_url', models.URLField(max_length=500, verbose_name='URL do Vídeo (YouTube, Google Drive, etc.)')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
