# Generated by Django 5.1.2 on 2025-04-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0039_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(max_length=500, verbose_name='URL do Vídeo (Apenas YouTube)'),
        ),
    ]
