# Generated by Django 5.1.2 on 2025-04-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0040_alter_tutorial_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
