# Generated by Django 5.1.2 on 2025-06-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0042_alter_customuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInstance',
        ),
    ]
