# Generated by Django 5.1.2 on 2025-06-16 01:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_delete_userinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMensagemAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tentativa', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('instance_name_usada', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_enviado', models.CharField(blank=True, max_length=15, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_mensagens_automaticas', to=settings.AUTH_USER_MODEL)),
                ('mensagem_configurada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.mensagemconfigurada')),
            ],
        ),
    ]
