# Generated by Django 5.1.2 on 2025-06-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0044_historicomensagemautomatica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='instance_name',
        ),
    ]
