# Generated by Django 5.1.2 on 2025-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0045_remove_customuser_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemconfigurada',
            name='mensagem_texto',
            field=models.TextField(default=''),
        ),
    ]
