# Generated by Django 5.1.2 on 2025-06-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0046_alter_mensagemconfigurada_mensagem_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoMensagemAutomatica',
        ),
    ]
