# Generated by Django 5.1.2 on 2025-06-29 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0047_delete_historicomensagemautomatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_final_enviada', models.TextField(blank=True, null=True)),
                ('data_tentativa', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_mensagem', to=settings.AUTH_USER_MODEL)),
                ('mensagem_configurada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.mensagemconfigurada')),
            ],
        ),
    ]
