# Generated by Django 5.1.2 on 2025-11-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0048_historicomensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='link_acesso',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
