# Generated by Django 5.1.2 on 2025-12-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0049_customuser_link_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_avatar_base64',
            field=models.TextField(blank=True, help_text='Dados base64 da foto para cache local', null=True, verbose_name='Avatar Base64'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_avatar_error',
            field=models.TextField(blank=True, help_text='Mensagem de erro da última tentativa', null=True, verbose_name='Erro do Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_avatar_expires',
            field=models.DateTimeField(blank=True, help_text='Data em que o cache do avatar expira', null=True, verbose_name='Avatar expira em'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_avatar_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('found', 'Encontrada'), ('not_found', 'Não encontrada'), ('error', 'Erro'), ('no_whatsapp', 'Sem WhatsApp')], default='pending', help_text='Status da última busca de foto', max_length=20, verbose_name='Status do Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_avatar_updated',
            field=models.DateTimeField(blank=True, help_text='Data da última atualização da foto', null=True, verbose_name='Última atualização do avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_avatar_url',
            field=models.URLField(blank=True, help_text='URL da foto de perfil do WhatsApp', max_length=500, null=True, verbose_name='URL do Avatar do WhatsApp'),
        ),
    ]
