# Generated by Django 5.1.2 on 2025-12-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0050_customuser_whatsapp_avatar_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
