# Generated by Django 5.1.2 on 2025-12-09 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0053_movimentacaocaixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaomensagem',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
