# Generated by Django 5.1.2 on 2025-12-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0054_alter_configuracaomensagem_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaocaixa',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
