# Generated by Django 5.1.2 on 2025-12-21 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0056_alter_customuser_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('login', 'Login no Sistema'), ('logout', 'Logout do Sistema'), ('create', 'Criação de Registro'), ('update', 'Edição de Registro'), ('delete', 'Exclusão de Registro'), ('view', 'Visualização de Página'), ('acesso', 'Acesso ao Sistema'), ('pagamento', 'Pagamento Realizado'), ('renovacao', 'Renovação de Cliente'), ('importacao', 'Importação de Dados'), ('exportacao', 'Exportação de Dados'), ('envio_msg', 'Envio de Mensagem'), ('agendamento_msg', 'Agendamento de Mensagem')], max_length=50, verbose_name='Tipo de Ação')),
                ('descricao', models.TextField(verbose_name='Descrição da Ação')),
                ('modelo_afetado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Afetado')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Objeto')),
                ('dados_antes', models.JSONField(blank=True, null=True, verbose_name='Dados Antes da Ação')),
                ('dados_depois', models.JSONField(blank=True, null=True, verbose_name='Dados Depois da Ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('duracao', models.FloatField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('erro', 'Erro')], default='sucesso', max_length=20)),
                ('url_acessada', models.URLField(blank=True, null=True, verbose_name='URL Acessada')),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True, verbose_name='Método HTTP')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_atividade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['usuario', 'data_hora'], name='clientes_lo_usuario_cfebf8_idx'), models.Index(fields=['tipo_acao', 'data_hora'], name='clientes_lo_tipo_ac_2c5f9d_idx')],
            },
        ),
    ]
