# Generated by Django 4.2.16 on 2026-01-17 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0059_fix_default_auto_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialentry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='financialentry',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='entry_type',
            field=models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='include_in_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
