# Generated by Django 4.2.16 on 2026-01-18 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0060_alter_financialentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialentry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='financialentry',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='financialentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
