# Generated by Django 4.2.16 on 2026-01-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0061_remove_financialentry_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialentry',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='financialscenario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='financialscenario',
            name='updated_at',
        ),
    ]
