# Generated by Django 4.2.16 on 2026-01-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0062_alter_financialentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialscenario',
            options={},
        ),
    ]
