# Generated by Django 4.2.16 on 2026-06-01 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0064_jogofavorito_historicojogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='tag',
            name='cor',
            field=models.CharField(default='#6c757d', help_text='Cor em hexadecimal (ex: #FF5733)', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_indicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da indicação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cliente_indicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente indicado')),
                ('cliente_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente que indicou')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
                'ordering': ['-data_indicacao'],
                'unique_together': {('cliente_indicador', 'cliente_indicado')},
            },
        ),
    ]
