# Generated by Django 4.2.16 on 2026-06-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0065_alter_tag_options_tag_cor_tag_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
