# Generated by Django 4.2.16 on 2026-06-02 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0066_alter_tag_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIndicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comissao', models.CharField(choices=[('indicacao', 'Por Indicação'), ('renovacao', 'Por Renovação'), ('ambos', 'Ambos (Indicação + Renovação)')], default='indicacao', max_length=20)),
                ('valor_por_indicacao', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor que o indicador ganha por cada indicação', max_digits=10)),
                ('valor_por_renovacao', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor que o indicador ganha quando o indicado renova', max_digits=10)),
                ('ativar_meta', models.BooleanField(default=False, help_text='Ativar sistema de meta por quantidade')),
                ('quantidade_meta', models.IntegerField(default=3, help_text='Quantidade de indicações para ganhar o bônus')),
                ('bonus_meta', models.DecimalField(decimal_places=2, default=0.0, help_text='Bônus ao atingir a meta', max_digits=10)),
                ('validade_meses', models.IntegerField(default=1, help_text='Validade do bônus em meses (0 = sem validade)')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_indicacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Indicação',
                'verbose_name_plural': 'Configurações de Indicação',
            },
        ),
    ]
