# Generated by Django 4.2.16 on 2026-06-03 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0067_configuracaoindicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoindicacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='configuracaoindicacao',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_indicacao', to=settings.AUTH_USER_MODEL, verbose_name='Cliente indicador'),
        ),
        migrations.AddField(
            model_name='configuracaoindicacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuracaoindicacao',
            name='ativar_meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracaoindicacao',
            name='bonus_meta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaoindicacao',
            name='quantidade_meta',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='configuracaoindicacao',
            name='validade_meses',
            field=models.IntegerField(default=1, help_text='0 = sem validade'),
        ),
    ]
