# Generated by Django 4.2.16 on 2026-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0069_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='code_type',
            field=models.CharField(choices=[('login', 'Login'), ('whatsapp', 'WhatsApp')], default='login', max_length=10),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
