# Generated by Django 4.2.16 on 2026-06-04 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0070_verificationcode_code_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cadastro_online',
            field=models.BooleanField(default=False, help_text='Indica se o usuário se cadastrou pelo site', verbose_name='Cadastro Online'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
