# Generated by Django 4.2.16 on 2026-06-05 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0071_customuser_cadastro_online_customuser_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(choices=[('1h', 'A cada 1 hora'), ('3h', 'A cada 3 horas'), ('6h', 'A cada 6 horas'), ('12h', 'A cada 12 horas'), ('24h', 'A cada 24 horas'), ('48h', 'A cada 48 horas'), ('7d', 'A cada 7 dias'), ('30d', 'A cada 30 dias')], default='24h', max_length=10)),
                ('manter_ultimos', models.IntegerField(default=7, help_text='Quantos backups manter')),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True)),
                ('proximo_backup', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento de Backup',
                'verbose_name_plural': 'Agendamentos de Backup',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('tamanho', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('running', 'Executando')], default='running', max_length=20)),
                ('erro', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Backup',
                'verbose_name_plural': 'Históricos de Backup',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
