# Generated by Django 4.2.16 on 2026-06-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0072_backupschedule_backuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
