# Generated by Django 4.2.16 on 2026-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0073_backuphistory_google_drive_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuphistory',
            name='google_drive_file_id',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='horario_envio_mensagens',
        ),
        migrations.AddField(
            model_name='backuphistory',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
