# Generated by Django 4.2.16 on 2026-06-06 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0074_remove_backuphistory_google_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço/Plano', 'verbose_name_plural': 'Serviços/Planos'},
        ),
        migrations.AddField(
            model_name='servico',
            name='controlar_estoque',
            field=models.BooleanField(default=False, verbose_name='Controlar Estoque'),
        ),
        migrations.AddField(
            model_name='servico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servico',
            name='estoque',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exigir_cpf',
            field=models.BooleanField(default=False, verbose_name='Exigir CPF'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exigir_email',
            field=models.BooleanField(default=False, verbose_name='Exigir E-mail'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exigir_nome',
            field=models.BooleanField(default=True, verbose_name='Exigir Nome'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exigir_senha',
            field=models.BooleanField(default=False, verbose_name='Exigir Senha'),
        ),
        migrations.AddField(
            model_name='servico',
            name='exigir_usuario',
            field=models.BooleanField(default=False, verbose_name='Exigir Usuário'),
        ),
        migrations.AddField(
            model_name='servico',
            name='multiplicador',
            field=models.IntegerField(blank=True, default=1, help_text='Quantas vendas cada unidade permite (ex: 1 unidade = 2 vendas)', verbose_name='Multiplicador'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_plano',
            field=models.CharField(choices=[('assinatura', 'Assinatura'), ('venda_vista', 'Venda à Vista'), ('venda_prazo', 'Venda a Prazo')], default='assinatura', max_length=20, verbose_name='Tipo de Plano'),
        ),
        migrations.AddField(
            model_name='servico',
            name='usuario_unico',
            field=models.BooleanField(default=True, help_text='Se marcado, não permite usuários duplicados', verbose_name='Usuário Único'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor do Plano'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='custos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custos'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Venda'),
        ),
    ]
