# Generated by Django 4.2.16 on 2026-06-06 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0075_alter_servico_options_servico_controlar_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de Créditos')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Lote (R$)')),
                ('quantidade_restante', models.IntegerField(default=0, verbose_name='Créditos Restantes')),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de consumo: menor número = consumido primeiro', verbose_name='Ordem (FIFO)')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['ordem', 'data_compra'],
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='codigo_produto',
            field=models.CharField(blank=True, help_text='Código único para identificar o produto', max_length=50, null=True, verbose_name='Código do Produto (SKU)'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_estoque',
            field=models.CharField(choices=[('unidades', 'Unidades (Produto Físico)'), ('creditos', 'Créditos (Assinatura/Recarga)'), ('ambos', 'Ambos (Unidades + Créditos)')], default='creditos', help_text='Unidades = produto físico | Créditos = assinatura/recarga', max_length=20, verbose_name='Tipo de Estoque'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='estoque',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade em Estoque (Unidades)'),
        ),
        migrations.CreateModel(
            name='VendaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade de Créditos')),
                ('custo_unitario_aplicado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário Aplicado (R$)')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_creditos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='clientes.loteestoque', verbose_name='Lote Utilizado')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_creditos', to='clientes.servico', verbose_name='Serviço/Plano')),
            ],
            options={
                'verbose_name': 'Venda de Crédito',
                'verbose_name_plural': 'Vendas de Créditos',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='clientes.servico', verbose_name='Serviço/Plano'),
        ),
    ]
