# Generated by Django 4.2.16 on 2026-06-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0076_loteestoque_servico_codigo_produto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['nome'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_externo',
            field=models.CharField(blank=True, help_text='Login usado para acessar o serviço. Pode ser compartilhado entre vários clientes.', max_length=150, null=True, verbose_name='Login do Serviço (IPTV)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='senha_leitura',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha do Serviço (IPTV)'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['login_externo', 'plano', 'dono'], name='clientes_cu_login_e_123351_idx'),
        ),
    ]
