# Generated by Django 4.2.16 on 2026-06-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0077_alter_customuser_options_customuser_login_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofinanceiro',
            name='grupo_renovacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo de Renovação'),
        ),
        migrations.AddField(
            model_name='relatoriofinanceiro',
            name='numero_renovacao',
            field=models.IntegerField(default=0, verbose_name='Nº da Renovação'),
        ),
    ]
