# Generated by Django 4.2.16 on 2026-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0078_relatoriofinanceiro_grupo_renovacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriofinanceiro',
            name='numero_renovacao',
        ),
        migrations.AddField(
            model_name='relatoriofinanceiro',
            name='numero_rodada',
            field=models.IntegerField(db_index=True, default=0, help_text='Identifica a rodada de renovação do grupo', verbose_name='Número da Rodada'),
        ),
        migrations.AlterField(
            model_name='relatoriofinanceiro',
            name='grupo_renovacao',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Grupo de Renovação'),
        ),
        migrations.AddIndex(
            model_name='relatoriofinanceiro',
            index=models.Index(fields=['grupo_renovacao', 'numero_rodada'], name='clientes_re_grupo_r_38f86b_idx'),
        ),
    ]
