# Generated by Django 4.2.16 on 2026-06-21 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0079_remove_relatoriofinanceiro_numero_renovacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_suporte', models.CharField(blank=True, help_text='Número com DDD (ex: 5564999999999)', max_length=20, null=True, verbose_name='WhatsApp Suporte')),
                ('telegram_suporte', models.CharField(blank=True, help_text='@username ou link do Telegram', max_length=100, null=True, verbose_name='Telegram Suporte')),
                ('ultimo_aviso_exibido', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_avisos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração de Avisos',
                'verbose_name_plural': 'Configurações de Avisos',
            },
        ),
        migrations.CreateModel(
            name='AvisoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Aviso')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('info', 'ℹ️ Informativo'), ('success', '✅ Sucesso'), ('warning', '⚠️ Alerta'), ('danger', '❌ Urgente')], default='info', max_length=20, verbose_name='Tipo')),
                ('icone', models.CharField(default='fa-bell', max_length=50, verbose_name='Ícone Font Awesome')),
                ('cor_destaque', models.CharField(default='#667eea', max_length=7, verbose_name='Cor de Destaque')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('mostrar_a_cada_login', models.BooleanField(default=False, help_text='Se marcado, mostra sempre que o usuário logar', verbose_name='Mostrar a cada login')),
                ('mostrar_intervalo_horas', models.IntegerField(blank=True, help_text='Deixe vazio para não usar intervalo', null=True, verbose_name='Mostrar a cada X horas')),
                ('mostrar_antes_vencimento', models.IntegerField(blank=True, help_text='Mostra para clientes que vencem em X dias', null=True, verbose_name='Mostrar X dias antes do vencimento')),
                ('mostrar_no_vencimento', models.BooleanField(default=False, verbose_name='Mostrar no dia do vencimento')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim (opcional)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aviso do Sistema',
                'verbose_name_plural': 'Avisos do Sistema',
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
    ]
