# Generated by Django 4.2.16 on 2026-06-21 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0080_configuracaoaviso_avisosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visto', models.DateTimeField(auto_now_add=True)),
                ('oculto_permanentemente', models.BooleanField(default=False)),
                ('contador', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Aviso Visualizado',
                'verbose_name_plural': 'Avisos Visualizados',
            },
        ),
        migrations.AddField(
            model_name='avisosistema',
            name='mostrar_primeiro_login',
            field=models.BooleanField(default=False, help_text='Mostra apenas nas primeiras X vezes que o usuário logar', verbose_name='Mostrar no primeiro login'),
        ),
        migrations.AddField(
            model_name='avisosistema',
            name='permitir_ocultar',
            field=models.BooleanField(default=True, help_text="Se marcado, o cliente pode marcar 'Não mostrar novamente'", verbose_name='Permitir cliente ocultar'),
        ),
        migrations.AddField(
            model_name='avisosistema',
            name='repeticoes',
            field=models.IntegerField(default=1, help_text='Quantas vezes mostrar (para primeiro login ou intervalo)', verbose_name='Quantidade de repetições'),
        ),
        migrations.AlterField(
            model_name='avisosistema',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='avisosistema',
            name='mostrar_a_cada_login',
            field=models.BooleanField(default=False, verbose_name='Mostrar a cada login'),
        ),
        migrations.AlterField(
            model_name='avisosistema',
            name='mostrar_antes_vencimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mostrar X dias antes do vencimento'),
        ),
        migrations.AlterField(
            model_name='avisosistema',
            name='mostrar_intervalo_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mostrar a cada X horas'),
        ),
        migrations.DeleteModel(
            name='ConfiguracaoAviso',
        ),
        migrations.AddField(
            model_name='avisovisto',
            name='aviso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='clientes.avisosistema'),
        ),
        migrations.AddField(
            model_name='avisovisto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_vistos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='avisovisto',
            unique_together={('aviso', 'cliente')},
        ),
    ]
