# Generated by Django 4.2.16 on 2026-06-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0081_avisovisto_avisosistema_mostrar_primeiro_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisosistema',
            name='global_para_todos',
            field=models.BooleanField(default=False, help_text='Se marcado, aparece para TODOS os usuários do sistema', verbose_name='Aviso Global'),
        ),
    ]
