# Generated by Django 4.2.16 on 2026-06-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0082_avisosistema_global_para_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisosistema',
            name='global_para_todos',
        ),
    ]
