# Generated by Django 4.2.16 on 2026-06-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0083_remove_avisosistema_global_para_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaomensagem',
            name='mensagem_bem_vindo',
            field=models.TextField(blank=True, help_text='Enviada automaticamente ao cadastrar um novo cliente', null=True, verbose_name='Mensagem de Boas-vindas'),
        ),
        migrations.AddField(
            model_name='configuracaomensagem',
            name='mensagem_confirmacao_pagamento',
            field=models.TextField(blank=True, help_text='Enviada após confirmar renovação/pagamento', null=True, verbose_name='Mensagem de Confirmação de Pagamento'),
        ),
    ]
