# Generated by Django 4.2.16 on 2026-06-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0084_configuracaomensagem_mensagem_bem_vindo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['data_criacao'], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutoriais'},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
