# Generated by Django 4.2.16 on 2026-06-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0085_alter_tutorial_options_alter_tutorial_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['ordem', 'data_criacao'], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutoriais'},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
