# Generated by Django 4.2.16 on 2026-06-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0086_alter_tutorial_options_tutorial_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialscenario',
            name='user',
        ),
        migrations.DeleteModel(
            name='FinancialEntry',
        ),
        migrations.DeleteModel(
            name='FinancialScenario',
        ),
    ]
