# Generated by Django 4.2.16 on 2026-07-21 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0087_remove_financialscenario_user_delete_financialentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
