# Generated by Django 4.2.16 on 2026-07-27 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0088_alter_movimentacaocaixa_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoPlaylistCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(choices=[('ibo_player', 'IBO Player'), ('fun_plays', 'Fun Plays')], max_length=40)),
                ('nome_playlist', models.CharField(default='Minha lista', max_length=150)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('device_key', models.CharField(blank=True, max_length=150)),
                ('dns', models.URLField(blank=True, max_length=500)),
                ('codigo', models.CharField(blank=True, max_length=150)),
                ('usuario_template', models.CharField(default='{usuario}', max_length=255)),
                ('senha_template', models.CharField(default='{senha}', max_length=255)),
                ('url_template', models.TextField(blank=True)),
                ('proteger', models.BooleanField(default=False)),
                ('pin_protecao', models.CharField(blank=True, max_length=255)),
                ('playlist_remote_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('nao_configurado', 'Não configurado'), ('configurado', 'Configurado'), ('aguardando_captcha', 'Aguardando CAPTCHA'), ('processando', 'Processando'), ('ativo', 'Lista ativa'), ('erro', 'Erro'), ('excluido', 'Excluído')], default='nao_configurado', max_length=30)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('dados_remotos', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_playlist', to=settings.AUTH_USER_MODEL)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_playlist_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cliente__nome', 'provedor'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoIntegracaoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('pesquisar', 'Pesquisar dispositivo'), ('adicionar', 'Adicionar lista'), ('excluir', 'Excluir lista'), ('substituir', 'Substituir lista'), ('consultar', 'Consultar lista')], max_length=30)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('parcial', 'Parcial')], max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('requisicao_resumo', models.JSONField(blank=True, default=dict)),
                ('resposta_api', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.integracaoplaylistcliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='integracaoplaylistcliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'provedor', 'mac_address'), name='integracao_playlist_cliente_provedor_mac_unica'),
        ),
    ]
