# Generated by Django 4.2.16 on 2026-07-28 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0089_integracaoplaylistcliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoplaylistcliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_playlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integracaoplaylistcliente',
            name='status',
            field=models.CharField(choices=[('nao_configurado', 'Não configurado'), ('configurado', 'Configurado'), ('aguardando_captcha', 'Aguardando CAPTCHA'), ('processando', 'Processando'), ('ativo', 'Lista ativa'), ('confirmacao_pendente', 'Confirmação pendente'), ('erro', 'Erro'), ('excluido', 'Excluído')], default='nao_configurado', max_length=30),
        ),
    ]
