# Generated by Django 4.2.16 on 2026-07-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0090_alter_integracaoplaylistcliente_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integracaoplaylistcliente',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='integracaoplaylistcliente',
            name='nome_avulso',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='integracaoplaylistcliente',
            name='senha_iptv',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='integracaoplaylistcliente',
            name='usuario_iptv',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
