# Generated by Django 4.2.16 on 2026-07-30 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0091_alter_integracaoplaylistcliente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistRemota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha lista', max_length=150)),
                ('nome_remoto', models.CharField(blank=True, default='', max_length=150)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('usuario_iptv', models.CharField(blank=True, default='', max_length=255)),
                ('senha_iptv', models.CharField(blank=True, default='', max_length=255)),
                ('dns', models.URLField(blank=True, max_length=500)),
                ('codigo', models.CharField(blank=True, max_length=150)),
                ('url_playlist', models.TextField(blank=True)),
                ('modo_envio', models.CharField(blank=True, default='url', max_length=20)),
                ('protegida', models.BooleanField(default=False)),
                ('pin_protecao', models.CharField(blank=True, default='', max_length=255)),
                ('pin_conhecido', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('processando', 'Processando'), ('ativo', 'Ativa'), ('confirmacao_pendente', 'Confirmação pendente'), ('nao_encontrada', 'Não encontrada'), ('erro', 'Erro'), ('excluida', 'Excluída')], default='rascunho', max_length=30)),
                ('encontrada_na_ultima_sync', models.BooleanField(default=True)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('dados_remotos', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='integracaoplaylistcliente',
            options={'ordering': ['nome_avulso', '-criado_em']},
        ),
        migrations.RemoveConstraint(
            model_name='integracaoplaylistcliente',
            name='integracao_playlist_cliente_provedor_mac_unica',
        ),
        migrations.AlterField(
            model_name='historicointegracaoplaylist',
            name='acao',
            field=models.CharField(choices=[('pesquisar', 'Pesquisar dispositivo'), ('sincronizar', 'Sincronizar playlists'), ('adicionar', 'Adicionar playlist'), ('editar', 'Editar playlist'), ('substituir', 'Substituir playlist'), ('excluir', 'Excluir playlist'), ('pin', 'Alterar proteção/PIN'), ('consultar', 'Consultar playlist')], max_length=30),
        ),
        migrations.AlterField(
            model_name='integracaoplaylistcliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integracoes_playlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integracaoplaylistcliente',
            name='provedor',
            field=models.CharField(choices=[('ibo_player', 'IBO Player'), ('fun_plays', 'Fun Plays'), ('focox_player', 'FocoX Player'), ('lazer_player', 'Lazer Player')], max_length=40),
        ),
        migrations.AlterField(
            model_name='integracaoplaylistcliente',
            name='status',
            field=models.CharField(choices=[('nao_configurado', 'Não configurado'), ('configurado', 'Configurado'), ('processando', 'Processando'), ('ativo', 'Ativo'), ('erro', 'Erro'), ('excluido', 'Excluído')], default='nao_configurado', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='integracaoplaylistcliente',
            constraint=models.UniqueConstraint(fields=('dono', 'provedor', 'mac_address'), name='integracao_playlist_dono_provedor_mac_unica'),
        ),
        migrations.AddField(
            model_name='playlistremota',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists_remotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistremota',
            name='integracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='clientes.integracaoplaylistcliente'),
        ),
        migrations.AddField(
            model_name='historicointegracaoplaylist',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='clientes.playlistremota'),
        ),
        migrations.AddIndex(
            model_name='playlistremota',
            index=models.Index(fields=['integracao', 'status'], name='clientes_pl_integra_eeee85_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistremota',
            index=models.Index(fields=['remote_id'], name='clientes_pl_remote__72b683_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistremota',
            index=models.Index(fields=['nome'], name='clientes_pl_nome_1ae419_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlistremota',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id', ''), _negated=True), fields=('integracao', 'remote_id'), name='playlist_integracao_remote_id_unico'),
        ),
    ]
