# Generated by Django 4.2.16 on 2026-09-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0093_configuracao_device_key_padrao_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='device_key_padrao',
            field=models.CharField(blank=True, help_text='Key usada automaticamente em novos cadastros de aplicativos quando nenhuma Key for informada.', max_length=150, null=True, verbose_name='Device Key padrão'),
        ),
    ]
