# Generated by Django 5.1.2 on 2025-06-08 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_url', models.CharField(max_length=255)),
                ('status', models.CharField(default='NOT_CREATED', max_length=50)),
                ('pushname', models.CharField(blank=True, max_length=255, null=True)),
                ('wid', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
