# Generated by Django 5.1.2 on 2025-06-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstance',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userinstance',
            name='api_url',
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='instance_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='pushname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='status',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='wid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
