# Generated by Django 5.1.2 on 2025-06-28 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0002_remove_userinstance_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemConfigurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criterio_dias', models.IntegerField(default=0)),
                ('horario_envio', models.TimeField(default='09:00')),
                ('texto_mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMensagemAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tentativa', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PENDENTE', max_length=50)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('mensagem_final_enviada', models.TextField(blank=True, null=True)),
                ('api_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_mensagens', to=settings.AUTH_USER_MODEL)),
                ('mensagem_configurada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_integration.mensagemconfigurada')),
            ],
            options={
                'ordering': ['-data_tentativa'],
            },
        ),
    ]
