# Generated by Django 5.1.2 on 2025-06-28 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0047_delete_historicomensagemautomatica'),
        ('whatsapp_integration', '0003_mensagemconfigurada_historicomensagemautomatica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='mensagem_configurada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_envios', to='clientes.mensagemconfigurada', verbose_name='Configuração de Mensagem'),
        ),
        migrations.AlterModelOptions(
            name='historicomensagemautomatica',
            options={'ordering': ['-data_tentativa'], 'verbose_name': 'Histórico de Mensagem Automática', 'verbose_name_plural': 'Históricos de Mensagens Automáticas'},
        ),
        migrations.AlterModelOptions(
            name='userinstance',
            options={'verbose_name': 'Instância de Usuário', 'verbose_name_plural': 'Instâncias de Usuário'},
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='api_message_id',
            field=models.CharField(blank=True, help_text='ID da mensagem na API Evolution (para rastreamento de status).', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_mensagens_automaticas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='data_envio',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que a API confirmou o envio da mensagem.', null=True, verbose_name='Data/Hora Envio Confirmado'),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='data_tentativa',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora Tentativa'),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='detalhes',
            field=models.TextField(blank=True, help_text='Detalhes sobre o envio, incluindo erros da API ou status.', null=True, verbose_name='Detalhes do Envio'),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='mensagem_final_enviada',
            field=models.TextField(blank=True, help_text='O texto da mensagem enviada após substituição das variáveis.', null=True, verbose_name='Mensagem Final Enviada'),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='status',
            field=models.CharField(default='PENDENTE', help_text='Status atual da tentativa de envio (Ex: PENDENTE, ENVIADO, ERRO)', max_length=50, verbose_name='Status do Envio'),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='instance_name',
            field=models.CharField(help_text='Nome único da instância na Evolution API (Ex: empresa123)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp da última atualização de status.'),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='pushname',
            field=models.CharField(blank=True, help_text='Nome de usuário/perfil da instância conectada.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Dados Base64 do QR Code, se aplicável.', null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='status',
            field=models.CharField(default='UNKNOWN', help_text='Status da conexão da instância (Ex: CONNECTED, QRCODE, DISCONNECTED)', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='wid',
            field=models.CharField(blank=True, help_text='WhatsApp ID (número) da instância conectada.', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MensagemConfigurada',
        ),
    ]
