# Generated by Django 5.1.2 on 2025-06-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0004_alter_historicomensagemautomatica_mensagem_configurada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
