# Generated by Django 5.1.2 on 2025-07-06 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0005_alter_historicomensagemautomatica_data_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemMassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('arquivo_midia', models.FileField(blank=True, null=True, upload_to='midias_mensagens/')),
                ('enviada', models.BooleanField(default=False)),
                ('clientes', models.ManyToManyField(related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
