# Generated by Django 5.1.2 on 2025-12-12 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0006_mensagemmassa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinstance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Instância WhatsApp', 'verbose_name_plural': 'Instâncias WhatsApp'},
        ),
        migrations.RemoveField(
            model_name='userinstance',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='userinstance',
            name='pushname',
        ),
        migrations.RemoveField(
            model_name='userinstance',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='userinstance',
            name='wid',
        ),
        migrations.AddField(
            model_name='userinstance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='last_check',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Verificação'),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='owner_jid',
            field=models.CharField(blank=True, help_text='Identificador único do WhatsApp conectado', max_length=200, null=True, verbose_name='JID do WhatsApp'),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='profile_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Perfil'),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='profile_pic_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL da Foto'),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='instance_name',
            field=models.CharField(max_length=100, verbose_name='Nome da Instância'),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='status',
            field=models.CharField(choices=[('created', 'Criada'), ('scanning_qr', 'Aguardando QR'), ('connected', 'Conectada'), ('connected_other', 'Conectada a Outro WhatsApp'), ('disconnected', 'Desconectada'), ('error', 'Erro')], default='created', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instance', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
