# Generated by Django 5.1.2 on 2025-12-12 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0007_alter_userinstance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='userinstance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='instance_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='last_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='owner_jid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='profile_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='profile_pic_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='status',
            field=models.CharField(choices=[('created', 'Criada'), ('scanning_qr', 'Aguardando QR'), ('connected', 'Conectada'), ('connected_other', 'Conectada a Outro WhatsApp'), ('disconnected', 'Desconectada')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instance', to=settings.AUTH_USER_MODEL),
        ),
    ]
