# Generated by Django 5.1.2 on 2025-12-12 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0008_alter_userinstance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinstance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Instância WhatsApp', 'verbose_name_plural': 'Instâncias WhatsApp'},
        ),
        migrations.AddField(
            model_name='userinstance',
            name='instance_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='status',
            field=models.CharField(choices=[('created', 'Criada'), ('scanning_qr', 'Aguardando QR'), ('connected', 'Conectada'), ('disconnected', 'Desconectada'), ('error', 'Erro')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
