# Generated by Django 5.1.2 on 2025-12-13 01:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0009_alter_userinstance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemmassa',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Mensagem em Massa', 'verbose_name_plural': 'Mensagens em Massa'},
        ),
        migrations.RenameField(
            model_name='mensagemmassa',
            old_name='data_agendada',
            new_name='data_agendamento',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='clientes',
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='agendada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='enviados_falha',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='enviados_sucesso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='filtros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='processando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviada', 'Enviada'), ('falha', 'Falha'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='total_clientes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='arquivo_midia',
            field=models.FileField(blank=True, null=True, upload_to='mensagens_massa/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_massa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='mensagemmassa',
            table='whatsapp_integration_mensagemmassa',
        ),
    ]
