# Generated by Django 5.1.2 on 2025-12-13 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0055_remove_movimentacaocaixa_created_at_and_more'),
        ('whatsapp_integration', '0010_alter_mensagemmassa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEnvioMassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_enviada', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('api_message_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Histórico de Envio em Massa',
                'verbose_name_plural': 'Históricos de Envio em Massa',
                'db_table': 'historico_envio_massa',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicomensagemautomatica',
            options={'ordering': ['-data_tentativa']},
        ),
        migrations.RenameField(
            model_name='mensagemmassa',
            old_name='data_agendamento',
            new_name='data_agendada',
        ),
        migrations.RenameField(
            model_name='mensagemmassa',
            old_name='enviados_falha',
            new_name='enviados_com_falha',
        ),
        migrations.RenameField(
            model_name='mensagemmassa',
            old_name='enviados_sucesso',
            new_name='enviados_com_sucesso',
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='clientes_destino',
            field=models.ManyToManyField(blank=True, related_name='mensagens_recebidas_massa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='tags_selecionadas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='whatsapp_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_massa', to='whatsapp_integration.userinstance'),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='whatsapp_instance_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='base_url',
            field=models.URLField(default='http://localhost:8080', help_text='URL da API Evolution (ex: http://localhost:8080)', verbose_name='URL Base da API'),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='api_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_mensagem_automatica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='data_tentativa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='mensagem_configurada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.mensagemconfigurada'),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='mensagem_final_enviada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicomensagemautomatica',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_massa_envio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('processando', 'Processando'), ('enviada', 'Enviada'), ('falha', 'Falha'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mensagemmassa',
            index=models.Index(fields=['remetente', 'status'], name='mensagem_ma_remeten_45079b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemmassa',
            index=models.Index(fields=['data_agendada'], name='mensagem_ma_data_ag_54110d_idx'),
        ),
        migrations.AlterModelTable(
            name='historicomensagemautomatica',
            table='historico_mensagem_automatica',
        ),
        migrations.AlterModelTable(
            name='mensagemmassa',
            table='mensagem_massa',
        ),
        migrations.AddField(
            model_name='historicoenviomassa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_envio_massa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoenviomassa',
            name='mensagem_massa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_envios', to='whatsapp_integration.mensagemmassa'),
        ),
        migrations.AddIndex(
            model_name='historicoenviomassa',
            index=models.Index(fields=['mensagem_massa', 'cliente'], name='historico_e_mensage_ff5ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoenviomassa',
            index=models.Index(fields=['status'], name='historico_e_status_d1c498_idx'),
        ),
    ]
