# Generated by Django 5.1.2 on 2025-12-14 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0055_remove_movimentacaocaixa_created_at_and_more'),
        ('whatsapp_integration', '0011_historicoenviomassa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoenviomassa',
            options={'ordering': ['-data_envio']},
        ),
        migrations.AlterModelOptions(
            name='mensagemmassa',
            options={'ordering': ['-data_agendamento'], 'verbose_name': 'Mensagem em Massa', 'verbose_name_plural': 'Mensagens em Massa'},
        ),
        migrations.RemoveIndex(
            model_name='historicoenviomassa',
            name='historico_e_mensage_ff5ea8_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicoenviomassa',
            name='historico_e_status_d1c498_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensagemmassa',
            name='mensagem_ma_remeten_45079b_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensagemmassa',
            name='mensagem_ma_data_ag_54110d_idx',
        ),
        migrations.RenameField(
            model_name='mensagemmassa',
            old_name='data_agendada',
            new_name='data_agendamento',
        ),
        migrations.RenameField(
            model_name='mensagemmassa',
            old_name='data_envio',
            new_name='data_envio_fim',
        ),
        migrations.RemoveField(
            model_name='historicoenviomassa',
            name='api_message_id',
        ),
        migrations.RemoveField(
            model_name='historicoenviomassa',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='historicoenviomassa',
            name='mensagem_enviada',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='arquivo_midia',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='clientes_destino',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='enviada',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='filtros',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='processando',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='tags_selecionadas',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='total_clientes',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='whatsapp_instance',
        ),
        migrations.RemoveField(
            model_name='mensagemmassa',
            name='whatsapp_instance_name',
        ),
        migrations.AddField(
            model_name='historicoenviomassa',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicoenviomassa',
            name='mensagem_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicoenviomassa',
            name='message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicoenviomassa',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='data_envio_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='dias_vencido_filtro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to='mensagens_massa/'),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='plano_filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.servico'),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='status_filtro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='tags_filtro',
            field=models.ManyToManyField(blank=True, to='clientes.tag'),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='tipo_midia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='total_destinatarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicoenviomassa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicoenviomassa',
            name='mensagem_massa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='whatsapp_integration.mensagemmassa'),
        ),
        migrations.AlterField(
            model_name='historicoenviomassa',
            name='status',
            field=models.CharField(choices=[('pendente', '⏳ Pendente'), ('enviado', '✅ Enviado'), ('falha', '❌ Falha'), ('entregue', '📲 Entregue'), ('lido', '👁️ Lido')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='enviados_com_falha',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='enviados_com_sucesso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_massa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='status',
            field=models.CharField(choices=[('rascunho', '📝 Rascunho'), ('agendada', '⏰ Agendada'), ('enviando', '🔄 Enviando'), ('concluida', '✅ Concluída'), ('cancelada', '❌ Cancelada'), ('falha', '⚠️ Falha')], default='rascunho', max_length=20),
        ),
        migrations.AlterModelTable(
            name='historicoenviomassa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mensagemmassa',
            table=None,
        ),
    ]
