# Generated by Django 4.2.16 on 2026-06-28 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp_integration', '0012_alter_historicoenviomassa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=200)),
                ('reply', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('revenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quick_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('groq', 'Groq (Grátis)'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='groq', max_length=20)),
                ('use_system_key', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('bot_name', models.CharField(default='Assistente Virtual', max_length=100)),
                ('system_prompt', models.TextField(default='Você é um assistente virtual profissional...')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_reply', models.BooleanField(default=True)),
                ('pause_until', models.DateTimeField(blank=True, null=True)),
                ('max_messages_per_day', models.IntegerField(default=200)),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('business_hours_start', models.TimeField(blank=True, null=True)),
                ('business_hours_end', models.TimeField(blank=True, null=True)),
                ('respond_outside_hours', models.BooleanField(default=False)),
                ('max_history_messages', models.IntegerField(default=10)),
                ('response_delay', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de IA',
                'verbose_name_plural': 'Configurações de IA',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('closed', 'Encerrada'), ('waiting_human', 'Aguardando Humano')], default='active', max_length=20)),
                ('messages', models.JSONField(default=list)),
                ('total_messages', models.IntegerField(default=0)),
                ('ai_messages', models.IntegerField(default=0)),
                ('human_messages', models.IntegerField(default=0)),
                ('first_message_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_conversations_cliente', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_integration.userinstance')),
                ('revenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_conversations_revenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('revenda', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='AIClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('ignore_client', models.BooleanField(default=False)),
                ('custom_prompt', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('max_messages_this_client', models.IntegerField(default=50)),
                ('messages_sent', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
                ('revenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_client_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('revenda', 'cliente')},
            },
        ),
    ]
