# Generated by Django 4.2.16 on 2026-06-28 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp_integration', '0013_aiquickreply_aiconfig_aiconversation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconfig',
            options={'verbose_name': 'Configuração Global de IA', 'verbose_name_plural': 'Configurações Globais de IA'},
        ),
        migrations.RemoveField(
            model_name='aiclientsettings',
            name='custom_prompt',
        ),
        migrations.RemoveField(
            model_name='aiclientsettings',
            name='max_messages_this_client',
        ),
        migrations.RemoveField(
            model_name='aiclientsettings',
            name='messages_sent',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='auto_reply',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='bot_name',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='business_hours_end',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='business_hours_start',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='messages_sent_today',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='pause_until',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='respond_outside_hours',
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_global_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='nome',
            field=models.CharField(default='Configuração Padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiclientsettings',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_client_settings_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiclientsettings',
            name='revenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_client_settings_revenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='revenda',
            field=models.OneToOneField(blank=True, help_text='Deixe vazio para config global. Preencha para config por revenda.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='system_prompt',
            field=models.TextField(default='Você é um assistente virtual profissional.\nResponda de forma educada e objetiva em português.\nNão invente informações. Se não souber, diga que não sabe.'),
        ),
        migrations.CreateModel(
            name='AIRevendaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_ativada', models.BooleanField(default=False, verbose_name='Ativar Assistente IA')),
                ('prompt_personalizado', models.TextField(blank=True, help_text='Personalize como o assistente responde para SEUS clientes', verbose_name='Seu Prompt Personalizado')),
                ('bot_name', models.CharField(default='Assistente Virtual', max_length=100)),
                ('mensagem_saudacao', models.TextField(blank=True, default='Olá! Sou o assistente virtual. Como posso ajudar?')),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('responder_fora_horario', models.BooleanField(default=False)),
                ('pausado_ate', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_personal_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração Pessoal de IA',
                'verbose_name_plural': 'Configurações Pessoais de IA',
            },
        ),
    ]
