# Generated by Django 4.2.16 on 2026-06-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0014_alter_aiconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='bot_marcacao',
            field=models.CharField(default='@bot', max_length=50),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='palavras_ativacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='precisa_marcacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='responder_grupos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='responder_privado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airevendasettings',
            name='bot_marcacao',
            field=models.CharField(default='@bot', max_length=50, verbose_name='Marcação do Bot'),
        ),
        migrations.AddField(
            model_name='airevendasettings',
            name='ignorar_bots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airevendasettings',
            name='palavras_ativacao',
            field=models.TextField(blank=True, default='', help_text='Palavras que ativam a IA (separadas por vírgula). Vazio = responde tudo.'),
        ),
        migrations.AddField(
            model_name='airevendasettings',
            name='palavras_chave_empresa',
            field=models.TextField(blank=True, help_text='Nomes que ativam a IA (ex: nome da loja, produto). Vazio = qualquer mensagem.'),
        ),
        migrations.AddField(
            model_name='airevendasettings',
            name='precisa_marcacao',
            field=models.BooleanField(default=True, verbose_name='Precisa marcar @bot no grupo'),
        ),
        migrations.AddField(
            model_name='airevendasettings',
            name='responder_grupos',
            field=models.BooleanField(default=False, verbose_name='Responder em Grupos'),
        ),
        migrations.AddField(
            model_name='airevendasettings',
            name='responder_privado',
            field=models.BooleanField(default=True, verbose_name='Responder no Privado'),
        ),
    ]
