# Generated by Django 4.2.16 on 2026-06-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0015_aiconfig_bot_marcacao_aiconfig_palavras_ativacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='messages_sent_today',
            field=models.IntegerField(default=0),
        ),
    ]
