# Generated by Django 4.2.16 on 2026-06-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0016_aiconfig_messages_sent_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstance',
            name='pushname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinstance',
            name='wid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
