# Generated by Django 4.2.16 on 2026-06-29 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0017_userinstance_pushname_userinstance_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
