# Generated by Django 4.2.16 on 2026-08-05 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp_integration', '0018_aiconfig_last_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemmassa',
            name='clientes',
            field=models.ManyToManyField(blank=True, help_text='Clientes selecionados pelos filtros', related_name='mensagens_massa_recebidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
