# Generated by Django 4.2.16 on 2026-08-06 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp_integration', '0019_mensagemmassa_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemmassa',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Mensagem em Massa', 'verbose_name_plural': 'Mensagens em Massa'},
        ),
        migrations.AddField(
            model_name='historicoenviomassa',
            name='mensagem_final',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='modo_destinatarios',
            field=models.CharField(choices=[('clientes', 'Clientes cadastrados'), ('avulsos', 'Somente números avulsos'), ('ambos', 'Clientes e números avulsos')], default='clientes', max_length=20),
        ),
        migrations.AddField(
            model_name='mensagemmassa',
            name='numeros_avulsos',
            field=models.TextField(blank=True, default='', help_text='Um número por linha, ou separados por vírgula/ponto e vírgula.'),
        ),
        migrations.AlterField(
            model_name='historicoenviomassa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagemmassa',
            name='clientes',
            field=models.ManyToManyField(blank=True, help_text='Clientes selecionados pelos filtros.', related_name='mensagens_massa_recebidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
